### ISSUE TITLE
[JH] Manage custom jupyterhub user profiles

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#100]
Users might might have custom requirements for their notebook servers. For example, they might need a bigger PVC or more CPU cores

These custom values need to be stored in a profile like [this](https://github.com/AICoE/idh-manifests/blob/production/jupyterhub/bases/custom-profiles/jupyterhub-singleuser-profiles.yaml). Because this will contain usernames, we will need to encrypt it.

**Comment by tumido** [comment]
Good idea!

We can make ksops encrypt the `users` field only via the `encrypted_regex` in `.sops.yaml` file. So the rest of the config is readable and reviewable. :wink:

**Comment by 4n4nd** [comment]
Unfortunately PVCs cannot be customized using user profiles yet, this feature is requested [here](https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/issues/78).
