### ISSUE TITLE
How to onboard Thoth services to monitoring

### ISSUE THREAD

**Issue by goern** [operate-first/apps#108]
As a Thoth Operator,
I want to add all my service endpoints to a monitoring system,
so that I can browse metrics of the services,
so that I can define thresholds for alarms to rise,
and so that alarms open issues on github.

**Comment by goern** [comment]
... and how do we do that for logging?

**Comment by goern** [comment]
Cc @harshad16

**Comment by 4n4nd** [comment]
@goern for logs we have some docs [here](https://github.com/operate-first/apps/tree/master/docs/observatorium/loki) that you can refer and start sending logs to our Loki instance.

for metrics and alerting we are working on the docs currently

**Comment by hemajv** [comment]
We now have docs on how to setup GitHub receiver and configure alerts: https://github.com/operate-first/SRE/tree/master/incident-management

**Comment by HumairAK** [comment]
What's remaining for this issue? Docs for metrics?

**Comment by harshad16** [comment]
> What's remaining for this issue? Docs for metrics?

how to persist the metrics with thanos is something yet to be done.

**Comment by HumairAK** [comment]
I think that will have to wait until we get around to #74

**Comment by harshad16** [comment]
yes, I understand.
let keep this issue open, I would have a closer look at all the requirements.
As technically alerts can be generated as the metrics flow in, just need to verify on what all alerts the thoth-station is looking into and if that needs persisted data.

**Comment by pacospace** [comment]
Reference: https://github.com/thoth-station/thoth-application/issues/854

cc @harshad16

**Comment by HumairAK** [comment]
Status on this issue and what is left to do? @harshad16 ?

**Comment by anishasthana** [comment]
Looks like we may have duplicate issues. I also opened https://github.com/operate-first/SRE/issues/135 to create a guide for user alerting

**Comment by goern** [comment]
From my point of view we not really have a user story for a developer for logging. How can I use for example Python logging or daiquiri do send my logs to a central place? How can I access and filter logs? how are they correlated with Pods I see on OpenShift? If my application raises an exception, can I alert on that?

**Comment by harshad16** [comment]
I will close this issue.
we have monitoring and alerts on a lower level.
we can improve it. This seems to be completed.
Thanks everyone.
