### ISSUE TITLE
Create/Update prometheus monitors for different ODH components

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#11]
First confirm with odh (likely via issue upstream) if there are plans to add such service monitors and the eta. Based on this feedback, we should discuss here whether we need to proceed with adding our own and sending them upstream. 

[anishasthana] At a minimum, we should update/create monitoring for the following:

- [x] Jupyterhub
- [x] Kafka
- [ ] Superset
- [ ] Data Catalog (once it's in)
- [x] Argo
- [ ] Airflow

**Comment by anishasthana** [comment]
Can we split this into individual issues per component? Would be easier to track progress that way imo.

**Comment by anishasthana** [comment]
@HumairAK  Let's rename the issue to say "Create prometheus monitors for different ODH components". In some cases, we _will_ need to use pod monitors

**Comment by anishasthana** [comment]
Also, kafka monitoring  was added in  https://github.com/opendatahub-io/odh-manifests/pull/230 :-)

**Comment by HumairAK** [comment]
The strategy has evolved a bit, we'll be using one service monitor for monitoring odh components, see [here](https://github.com/operate-first/apps/pull/123/files) and [the adr here](https://github.com/operate-first/blueprint/blob/main/docs/adr/0006-monitoring-structure.md) for more info.
