### ISSUE TITLE
[Monitoring] Grafana proxy breaks communication with the Grafana Operator

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#112]
Because of the grafana proxy, the operator is not able to communicate with the Grafana deployment and as a result, it cannot update dashboards as well as datasources. 
I think we were planning to keep grafana open and remove the proxy altogether, which would fix this issue.

**Comment by 4n4nd** [comment]
This was the error log:
```
{"level":"error","ts":1610571931.0078356,"logger":"controller_grafanadashboard","msg":"error updating dashboard","error":"error creating folder, expected status 200 but got 403","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/hstefans/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).manageError\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:366\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).reconcileDashboards\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:254\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).Reconcile\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:136\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func1\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:86\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func2\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:92"}
{"level":"error","ts":1610571931.0198598,"logger":"controller_grafanadashboard","msg":"failed to get or create namespace folder opf-monitoring for dashboard ","error":"error creating folder, expected status 200 but got 403","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/hstefans/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).reconcileDashboards\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:253\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).Reconcile\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:136\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func1\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:86\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func2\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:92"}
```
and @HumairAK can confirm that this was fixed after testing without the proxy

**Comment by tumido** [comment]
We'll see how it'll behave with the SSO later on. I think we still want to have that "login required" layer possible and enabled but if this occurs again, we'll solve it once we run into it.

**Comment by HumairAK** [comment]
>  I think we still want to have that "login required" layer possible 
Yes absolutely

**Comment by 4n4nd** [comment]
@tumido @HumairAK Can you please explain why we want the "login required" layer? Can we not keep it like the [observatorium grafana](https://grafana-route-opf-observatorium.apps.cnv.massopen.cloud/?orgId=1)? In that instance you can view all the dashboards and explore without having to log in. New dashboards/datasources can only be added using k8s resources ([example](https://github.com/operate-first/apps/blob/master/observatorium/overlays/moc/grafana-data-sources/opf-test-loki-source.yaml)).

**Comment by HumairAK** [comment]
Hrmm I might have misunderstood, what we want is grafana to be visible to the public, but login is required to make write changes.

**Comment by 4n4nd** [comment]
@HumairAK I remember we talked about keeping the grafana read-only and only edit dashboards using git ([comment](https://github.com/operate-first/apps/pull/67#issuecomment-741046230)). If we want to make this grafana editable, which makes since we want users to be able to prototype here, we should keep the Loki Grafana separate.

**Comment by HumairAK** [comment]
I think if we can secure datasources so that only admins can edit the loki datasource, then we can consolidate to one grafana (the one in opf-monitoringa). I think we still want people to be able to create dashboards live (but store them in git if they want them backed up).
