### ISSUE TITLE
Remove codeowners file

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#114]
According to @anishasthana  removing the codeowners file will remove the sesheta spam with regards to assigning a bunch of reviewers.

**Comment by anishasthana** [comment]
I'm not sure if it's sesheta or github being responsible for the spam, but once I removed the codeowners file things became a lot quieter

**Comment by tumido** [comment]
What is "the spam"?

The [`CODEOWNERS` file](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners) is a GitHub thing and it's responsible for assigning reviews based on path patterns and file ownership. I'm against removing it. I'd rather see us tuning it a bit better so the reviews are assigned to the appropriate owners (if you consider it a spam, you can remove yourself from it).

There's also the [`OWNERS` file](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/approve/approvers) which is a Prow thing (in our case that means the sesheta comments). I don't care that much about this thing.

**Comment by HumairAK** [comment]
Thanks for the info @tumido , that offers some clarification on the codeowners file. Let's keep it then and folks can have themselves removed if it's an issue. Closing.
