### ISSUE TITLE
Groups should not be in the namespace folder

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#115]
I think we should probably pull the groups out of the namespace folder, since it's not a 1:1 mapping between groups and namespaces, rather, one group can be owners of many namespaces, wdyt?

**Comment by tumido** [comment]
Yeah, I was thinking about something like that as well. I think we should reconsider the dir structure to accommodate this a bit better. We should also move the rbac to components etc. Let's discuss this in the ADR, I'll have that PR out today. For now the current layout is sufficient, there's no risk in keeping it as is for few days. Let's finalize the layout in the ADR and base the onboarding docs on that.

Related: https://github.com/operate-first/odh-moc-support/issues/39

**Comment by anishasthana** [comment]
I think discussing in the ADR makes sense.

**Comment by HumairAK** [comment]
Fixed by #120
