### ISSUE TITLE
Loki distributor broken

### ISSUE THREAD

**Issue by goern** [operate-first/apps#125]
as of now http://loki-distributor-opf-observatorium.apps.cnv.massopen.cloud/ returns 404

/kind bug
/priority critical-urgent

**Comment by goern** [comment]
uh, or... do I need to know/guess my org-id?

**Comment by tumido** [comment]
based on https://github.com/operate-first/apps/blob/master/docs/observatorium/loki/README.md I'd say you need to know the org id for the distributor as well as for the front end:

```
curl http://loki-distributor-opf-observatorium.apps.cnv.massopen.cloud/
404 page not found

curl http://loki-frontend-opf-observatorium.apps.cnv.massopen.cloud/
no org id
```

@4n4nd how can be Loki accessed?

**Comment by 4n4nd** [comment]
> based on https://github.com/operate-first/apps/blob/master/docs/observatorium/loki/README.md it says you need to know the org id for the distributor as well as for the frontend, but as the docs says as well "it can be set to anything".
> 
> 
> 
> cc @4n4nd
> 
> 
> 
> So, I'l guessing you choose the org id when pushing logs and when retrieving them, you just use the same org id. Is that it? :smile: 

That's exactly it @tumido

**Comment by HumairAK** [comment]
@goern does that solve your issue? if so please close this issue, thanks!

**Comment by 4n4nd** [comment]
I think we can close this issue now
