### ISSUE TITLE
Move MOC operators from moc-cnv-sandbox repo to this repo under cluster-scope app

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#126]
This will require a sibling PR in [this](https://github.com/open-infrastructure-labs/moc-cnv-sandbox) repo that removes the operators.

**Comment by tumido** [comment]
Operator status board for all operators found on MOC cluster:
| STATUS                                                                   | NAMESPACE           | NAME                            | PACKAGE                         | SOURCE              | CHANNEL        |
| ------------------------------------------------------------------------ | ------------------- | ------------------------------- | ------------------------------- | ------------------- | -------------- |
| No idea where it's defined                                               | local-storage       | local-storage-operator          | local-storage-operator          | redhat-operators    | 4.5            |
| No idea where it's defined                                               | openshift-cnv       | kubevirt-hyperconverged         | kubevirt-hyperconverged         | redhat-operators    | 2.4            |
| https://github.com/operate-first/apps/pull/131                           | openshift-metering  | metering-operator               | metering-ocp                    | redhat-operators    | 4.5            |
| https://github.com/operate-first/apps/pull/131                           | openshift-operators | opendatahub-operator            | opendatahub-operator            | community-operators | beta           |
| https://github.com/operate-first/apps/pull/131                           | openshift-operators | openshift-pipelines-operator-rh | openshift-pipelines-operator-rh | redhat-operators    | ocp-4.5        |
| In the ODH app                                                           | openshift-operators | strimzi                         | strimzi-kafka-operator          | community-operators | strimzi-0.19.x |
| No idea where it's defined                                               | openshift-storage   | ocs-operator                    | ocs-operator                    | redhat-operators    | stable-4.5     |
| In the ODH app                                                           | opf-datacatalog     | radanalytics-spark              | radanalytics-spark              | community-operators | alpha          |
| In the ODH app                                                           | opf-jupyterhub      | prometheus-operator             | prometheus                      | community-operators | beta           |
| In the ODH app                                                           | opf-monitoring      | grafana-operator                | grafana-operator                | community-operators | alpha          |
| In the ODH app                                                           | opf-monitoring      | prometheus-operator             | prometheus                      | community-operators | beta           |
| In the ODH app                                                           | opf-observatorium   | grafana-operator                | grafana-operator                | community-operators | alpha          |
| No idea where it's defined, probably in the thoth app (namespace scoped) | thoth-infra-prod    | prometheus-operator             | prometheus                      | community-operators | beta           |


@larsks  can you help me find out where are the specs for `local-storage-operator`, `kubevirt-hyperconverged` and `ocs-operator` + what other config is required for them and if we even want to care of them in this repo?

**Comment by tumido** [comment]
@HumairAK @larsks I'd need some help here from you guys ^. :slightly_smiling_face: :pray:

**Comment by larsks** [comment]
Operators currently installed via playbooks:

- [LSO](https://github.com/open-infrastructure-labs/moc-cnv-sandbox/tree/master/roles/ocp/lso)
- [OCS](https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/ocs/tasks/main.yml)

  Relies on `ocs_devices` variable defined [here](https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/group_vars/all/ocs_devices.yml)

- [CNV](https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/cnv/tasks/main.yml)

**Comment by 4n4nd** [comment]
@tumido can we another column names `scope` for the operators?
Some of these listed operators are namespace scoped.

**Comment by tumido** [comment]
@4n4nd yes, we can... This issue aims to replicate all that is already available on the cluster - without any modifications to it. I just have to know where to find the definitions... :slightly_smiling_face:  So if it's a namespaced operator, it has to be synced as a namespaced anyways.

**Comment by tumido** [comment]
waiting on ADR https://github.com/operate-first/blueprint/pull/26
