### ISSUE TITLE
Need access for curator team on curator cluster

### ISSUE THREAD

**Issue by skanthed** [operate-first/apps#1279]
Earlier we had cluster-admin access on the curator cluster. After updating to a newer version and solving OAuthServerConfig degraded issue in this PR - https://github.com/operate-first/apps/commit/0bdc9bdddad5eef2bc58a8d917ad486561489c80  we lost our access. 

Need access again!

**Comment by HumairAK** [comment]
Cluster admin file for curator is here: https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/moc/curator/groups/cluster-admins.yaml 

Anyone in this group has cluster admin to `curator` cluster. Can you make a PR?
