### ISSUE TITLE
Argo workflows pods succeed but UI says failed

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#128]
http://argo-portal-opf-argo.apps.cnv.massopen.cloud/workflows

**Comment by tumido** [comment]
This is a known issue with the ODH argo I think. The culprit is the SA used by Argo:
![image](https://user-images.githubusercontent.com/7453394/105209061-af7ee000-5b49-11eb-9cfc-75c8f6b0ae12.png)


This will be resolved via: https://github.com/opendatahub-io/odh-manifests/pull/208

**Comment by tumido** [comment]
Current ODH argo docs mention it as "you need to specify a service account, when submitting a workflow"

https://github.com/opendatahub-io/odh-manifests/tree/master/odhargo#run-a-workflow

This will be changed in my PR, because I'm assigning the SA as the default one.

**Comment by 4n4nd** [comment]
thanks for the clarification!

**Comment by 4n4nd** [comment]
This was because @anishasthana suggested that we need to run at least one workflow for the prometheus metrics to work.

**Comment by tumido** [comment]
btw, @4n4nd  the metrics may have also changed a bit between the ancient ODH Argo and the current latest. See http://workflow-controller-metrics-aiops-prod-argo.apps.ocp4.prod.psi.redhat.com/metrics for example. I'll update the Operate first Argo for you tomorrow, so we can coordinate that for future proofing. :slightly_smiling_face:

**Comment by tumido** [comment]
@4n4nd can you please verify if we resolved this by https://github.com/operate-first/apps/pull/137

**Comment by 4n4nd** [comment]
Just ran an example workflow and it [completed successfully](http://argo-portal-opf-argo.apps.cnv.massopen.cloud/workflows/opf-argo/sparkly-dragon?tab=workflow&nodeId=sparkly-dragon). I'll close this issue now :+1:
