### ISSUE TITLE
intro.md | "onboarding to a cluster" | Link to URL is not working

### ISSUE THREAD

**Issue by schwesig** [operate-first/apps#1298]
On
https://github.com/operate-first/apps/blob/master/docs/about/intro.md
the link
https://www.operate-first.cloud/users/support/docs/onboarding_to_cluster.md
leads to a 404 error page.

Assumed ToDos
- [ ] find correct link or create a new page
- [ ] correct it in intro.md (PR?!)

**Comment by HumairAK** [comment]
I think this was changed in the restructuring of the ops docs into jupyterbook, so the above links don't work as they dont' exist any more, closing. If this persists please provide the updated paths that need to be fixed, thanks.
