### ISSUE TITLE
Deploy Thanos on MOC/Smaug

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#1327]
We need an instance of Thanos where we can collect metrics from multiple clusters that we host.
This will also be a single source for all cluster metrics.
Tasks:

- [x] Deploy Thanos Receive (Component to receive metrics from cluster Prometheus instances and storing to object storage) (https://github.com/operate-first/apps/pull/1333)
- [x] Deploy Thanos Query and Query Frontend (Component to enable Prom API for metrics querying) (https://github.com/operate-first/apps/pull/1337)
- [ ] Deploy Thanos Compact (Component to compact as well as downsample metrics data stored in the object storage)
- [x] Deploy Thanos Store (Component to enable the thanos store API) (https://github.com/operate-first/apps/pull/1426)
- [x] Enable metrics remote write to Thanos Receive from moc/smaug Openshift Monitoring and UWM Prometheuses (https://github.com/operate-first/apps/pull/1338)
- [x] Add GrafanaDatasource for the thanos instance (https://github.com/operate-first/apps/pull/1354)
- [x] Enable metrics remote write to Thanos Receive from moc/infra Openshift Monitoring and UWM Prometheuses (https://github.com/operate-first/apps/pull/1391)
- [x] Enable metrics remote write to Thanos Receive from emea/balrog Openshift Monitoring and UWM Prometheuses (https://github.com/operate-first/apps/pull/1391)
- [x] Enable metrics remote write to Thanos Receive from emea/rick Openshift Monitoring and UWM Prometheuses (https://github.com/operate-first/apps/pull/1391)

After these are deployed, we will also need to deploy Observatorium API to manage access to thanos.

**Comment by HumairAK** [comment]
@4n4nd I think this is in large part done, can we close this?
