### ISSUE TITLE
Apicurio argocd application is not working after several fixes

### ISSUE THREAD

**Issue by famartinrh** [operate-first/apps#1349]
Hi,

I tried to fix the Apicurio argocd application, because it has not been deployed since the new migration to this new repo and new clusters...

I spotted various issues that were fixed in PRs #1320 #1324 #1343 but still Apicurio argocd application is not synced.

Could you help me troubleshoot the problem here?

Thank you

**Comment by famartinrh** [comment]
https://github.com/operate-first/apps/pull/1351

**Comment by HumairAK** [comment]
@famartinrh is there more assistance needed here, or is this issue now resolved?

**Comment by famartinrh** [comment]
it's fixed now, thanks!
