### ISSUE TITLE
youtube video mentions non exisiting link on webpage

### ISSUE THREAD

**Issue by schwesig** [operate-first/apps#1368]
## What happens
1. Go to https://aicoe-aiops.github.io/data-science-workflows/docs/getting-started.html
2. Click on [video tutorial][videotutorial] under section Develop on Operate First Jupyterhub
3. At minute [0:31][video0032] the YouTube mentions a link **_User_**, that doesn't exist (anymore?)

## What was expected
The video shows the right/current webpage.

## Quickfix
- [ ] Add a link or explanation in the description section of the video

## Screenshots
![image](https://user-images.githubusercontent.com/89909507/143606726-dee52339-14ed-4887-9898-2d9648990f3f.png)

[videotutorial]: https://www.youtube.com/watch?v=iI_-lqi3vP4&list=PL8VBRDTElCWpneB4dBu4u1kHElZVWfAwW&index=3&t=13s
[video0032]: https://youtu.be/iI_-lqi3vP4?t=32

**Comment by schwesig** [comment]
https://aicoe-aiops.github.io/data-science-workflows/docs/getting-started.html

Link "JupyterHub instance" under
"Access the public JupyterHub instance on the Massachusetts Open Cloud (MOC) by selecting moc-sso and then signing in with your Google Account"
leads to [link][jupyterhubinstance]
is not working

- [ ] change zero to smaug environment


[jupyterhubinstance]: https://oauth-openshift.apps.zero.massopen.cloud/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fjupyterhub-opf-jupyterhub.apps.zero.massopen.cloud%2Fhub%2Foauth_callback&client_id=system%3Aserviceaccount%3Aopf-jupyterhub%3Ajupyterhub-hub&state=eyJzdGF0ZV9pZCI6ICI0NjQzNjI0NDY5OTY0MmUxOWJhMzM5OTA0ZDZhZDcwZiIsICJuZXh0X3VybCI6ICIvaHViLyJ9&scope=user%3Ainfo

**Comment by suppathak** [comment]
@schwesig , I just realized it is the same issue that i opened [here](https://github.com/aicoe-aiops/data-science-workflows/issues/99).

**Comment by schwesig** [comment]
@suppathak ok, thanks! then I will close this one here.

closed because of issue doubled in https://github.com/aicoe-aiops/data-science-workflows/issues/99
