### ISSUE TITLE
Majority of operate-first.cloud pages are not found

### ISSUE THREAD

**Issue by craicoverflow** [operate-first/apps#1406]
Most webpages that are linked in the side nav do not direct to anything for me.

Examples:
- https://www.operate-first.cloud/hitchhikers-guide/apps/docs/acme/issuing_certificates.md
- https://www.operate-first.cloud/hitchhikers-guide/apps/docs/acm/adding_users_to_acm.md
- https://www.operate-first.cloud/hitchhikers-guide/apps/docs/ocs/claiming_object_store.md

**Comment by HumairAK** [comment]
Hey @craicoverflow apologies, the site is undergoing a bit of restructuring, this should be resolved by: https://github.com/operate-first/operate-first.github.io/pull/336

The new location for these docs is active though, you can access it here: https://www.operate-first.cloud/apps/content/README.html

**Comment by craicoverflow** [comment]
No problem, just was not sure if you guys were aware. Ooh thanks! I was going through the GH repo files, this is better.
