### ISSUE TITLE
Broken link at "How to encrypt apps in this repo"

### ISSUE THREAD

**Issue by rbo** [operate-first/apps#1410]
The first link at  https://github.com/operate-first/apps/blob/master/docs/content/argocd-gitops/encrypting_applications.md is broken.

Link to https://github.com/operate-first/continuous-deployment/blob/master/docs/manage_your_app_secrets.md is removed with commit https://github.com/operate-first/continuous-deployment/commit/585a2baad151159424e976dc03c0d7a2f68b7c34

**Comment by HumairAK** [comment]
FYI these links are found here: 
https://www.operate-first.cloud/apps/content/argocd-gitops/README.html

I'll send in a pr to update these links
Thanks!
