### ISSUE TITLE
Is there any documentation on Seldon?

### ISSUE THREAD

**Issue by oindrillac** [operate-first/apps#1413]
We have the seldon operator available in _Smaug_ under the `ds-ml-workflows-ws` namespace. Is any documentation which highlights how to access the opf seldon namespace and shares any details?

If not, it might be valuable for DS users if added under the list of managed odh components https://www.operate-first.cloud/apps/content/odh/README.html.

related: https://github.com/aicoe-aiops/data-science-workflows/pull/78

**Comment by HumairAK** [comment]
AFAIK we do not, how about we convert this issue from _question_ into an action on _adding docs_ for seldon? 

Volunteers? Docs would go here: https://github.com/operate-first/apps/tree/master/docs/content/odh 

Adding to the toc is relatively simple: https://github.com/operate-first/apps/blob/master/docs/CONTRIBUTING.md

**Comment by durandom** [comment]
@oindrillac @MichaelClifford is your team still using this seldon deployment?

/assign @oindrillac
