### ISSUE TITLE
Onboard Morty

### ISSUE THREAD

**Issue by rbo** [operate-first/apps#1471]
This issue is to track the onboarding of Morty cluster (EMEA)

- [x] SSO 
    - Wait for https://github.com/operate-first/support/issues/504
    - PR #1470
- [x] Alertmanager 
    - PR #1470 
- [ ] Check alert repository 
- [x] Install ODF
    - PR #1506 
- [X] Install NDF 
    - PR #1713
- [X] Install OpenShift Virtualization 
    - PR #1713
- [X] Install OpenShift pipelines 
    - PR #1713
- [X] Setup letsencrypt - For example: operate-first/support/issues/339 
    - PR#1702
- [ ] Adjust template: https://github.com/operate-first/support/blob/main/.github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml 

Current PR:
 - PR #1466 
 - PR #1470

**Comment by HumairAK** [comment]
sso/alert receiver configured

**Comment by rbo** [comment]
@4n4nd please add document all Morty related PR for onboarding/configuration here to have a complete list of task for cluster onboading.

**Comment by dystewart** [comment]
Added Morty cluster to the cluster dropdown in the template at [Issue: Onboard to a cluster](https://github.com/operate-first/support/issues/new?assignees=first-operator&labels=kind%2Fonboarding%2Carea%2Fcluster&template=onboarding_to_cluster.yaml&title=NEW+PROJECT%3A+%3Cname%3E)

[https://github.com/operate-first/support/pull/548](https://github.com/operate-first/support/pull/548)

**Comment by HumairAK** [comment]
I believe this is now complete. Feel free to re open if any items are left.
