### ISSUE TITLE
ODH Upgrade from `v1.1.0` to `v1.1.1`

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#1476]
This issue tracks the issues/changes required to accomodate the ODH upgrade to 1.1.1 for the following services: 
- JupyterHub
- Trino
- Superset
- Kafka

# JupyterHub 
To update Jupyterhub we saw the following issues:
1. The new HA Jupyterhub Server DeploymentConfig needs a configmap called [`sidecar-probe`](https://github.com/opendatahub-io/odh-manifests/blob/c4d94c3308e6555715dcadf6461115c926724253/jupyterhub/jupyterhub/base/jupyterhub-configmap.yaml#L21), this was added in the most recent release and since we were overriding the whole `jupyterhub-configmap.yaml` file, this required configmap was not being created which resulted in JH server deployment failure that in turn resulted in the Traefik proxies failing. ([Fix](https://github.com/operate-first/apps/pull/1473/commits/c2bc84eb5c25912716a9dd0bfa2fee6d06ed15a2))

2. Once the `sidecar-probe` configmap was added, we saw another error in the JH server pod events:
    ```
    Error: couldn't find key notebook_destination in ConfigMap opf-jupyterhub-stage/jupyterhub-cfg
    ```
    In the newest release a required parameter `notebook_destination` was added which needed to be present in the jupyterhub-cfg 
    configmap. ([Fix](https://github.com/operate-first/apps/pull/1473/commits/6e4f6beaaa1b46b162ec7655c6cbee200260e0a8))

3. After this the Notebook server and the Traefik proxies started working. But we were still not able to spawn notebooks because of the following error:
![screenshot_from_2021-12-21_10-59-09](https://user-images.githubusercontent.com/22333506/146973166-0fb2d7c1-ad36-47ac-808c-2bfe0ec1afbb.png)
  This meant that [the rolebinding required](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/jupyterhub/base/jupyterhub-cluster-rolebinding.yaml) was not being applied properly. We found that the ODH operator was overwriting the rolebinding for every instance of Jupyterhub on the cluster. In Operate First Smaug cluster, we have multiple (3 different) deployments of Jupyterhub. So we had to override that particular rolebinding yaml and add the correct serviceaccounts. ([fix](https://github.com/operate-first/apps/pull/1474))

# Trino
- hive-xml contents updated, we override this file so we had to merge with our downstream changes 
- jvm configs were separated for workers and coordinators, we add these configs manually so we need to update these configmaps, and also the coord/worker deployments to import them
- Also added prometheus-exporter secret mount to coord deployment, we needed to add this as well to our deployment override
- trino image also updated from `latest` to specific version 361, however we use 362 which we were specifying via kfdef parameter, this required us to now override the trino kustomization to use 362.

# Superset
- superset upgraded to 1.3
- superset image is not longer customizable via odh kfdef parameters
- superset and supersetdb configs moved to secrets
- various kfdef parameters were removed/renamed, had to update our kfdefs to adapt to this change
- superset default db name was updated to `superset`, old name was `supersetdb`, we had to update the default superset secret to accommodate this change. 

# Kafka
No additional changes required.

**Comment by HumairAK** [comment]
Upgrading trino resulted in a coordinator error: 

```
+ set +e
+ grep -s -q node.id /etc/trino/node.properties
+ NODE_ID_EXISTS=1
+ set -e
+ NODE_ID=
+ [[ 1 != 0 ]]
+ NODE_ID=-Dnode.id=trino-coordinator-bb8fc5b9-68pxk
+ exec /usr/lib/trino/bin/launcher run --etc-dir /etc/trino -Dnode.id=trino-coordinator-bb8fc5b9-68pxk --config=/etc/trino/config-coordinator.properties --jvm-config=/etc/trino/jvm-coordinator.config
Error occurred during initialization of VM
agent library failed to init: instrument
Error opening zip file or JAR manifest missing : /usr/lib/trino/lib/jmx_exporter.jar
```

This file: 
https://github.com/opendatahub-io/odh-manifests/blob/master/trino/base/trino-config-secret.yaml#L32

Doesn't seem available in the trino pod on the [352](https://quay.io/repository/opendatahub/trino?tag=latest&tab=tags) image: 

```
sh-4.2$ ls /usr/lib/trino/lib/ | grep jmx_exporter
sh-4.2$ 
```

**Comment by HumairAK** [comment]
This file is missing from trino 362, @rimolive mentioned on slack that they will add it.

```
Humair Khan  32 minutes ago
@Ricardo Martinelli de Oliveira do you know about this file? https://github.com/opendatahub-io/odh-manifests/blob/master/trino/base/trino-config-secret.yaml#L32

Humair Khan  31 minutes ago
we're using quay.io/opendatahub/trino:362 if that helps

Ricardo Martinelli de Oliveira  1 minute ago
yeah, it was added in Trino 361

Humair Khan  1 minute ago
why not 362?

Ricardo Martinelli de Oliveira  < 1 minute ago
We didn't upgrade yet, so I don't know.

Ricardo Martinelli de Oliveira  < 1 minute ago
I'll make sure to update trino 362
```

**Comment by HumairAK** [comment]
@operate-first/odh
