### ISSUE TITLE
Docs on how to provision ArgoCD read/admin access

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1501]
Add these docs to: https://github.com/operate-first/apps/blob/master/docs/content/argocd-gitops/get_access_to_argocd.md

Add a new section "Get Admin Access" with something like: 

"If you need admin level read access, add your GitHub handle to [this group](https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml)" 
"If you need admin level read/write access, add your GitHub handle to [this group](https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml)"

**Comment by Gregory-Pereira** [comment]
Resolved by #1524. Feel free to re-open if something was missed.
