### ISSUE TITLE
Trouble accessing the grafana dashboard

### ISSUE THREAD

**Issue by harshad16** [operate-first/apps#1511]
One of the developer of Thoth group is not able to login into grafana dashboard
user github id: Gkrumbach07

already added in the thoth group
https://github.com/operate-first/apps/commit/0b31c8b96f02cfeadfc4d3769b87000c30f9660e

however when the user tries to login always get the following issue:
![image](https://user-images.githubusercontent.com/14028058/148995152-26ca44b6-fb20-47f4-bd5e-d5ddcff98daa.png)

could be due to the capital letter in the id.

**Comment by Gkrumbach07** [comment]
Has this issue been resolved? Is there something I need to do on my end. Thanks

**Comment by Gregory-Pereira** [comment]
@Gkrumbach07 once #1593 gets merged try logging into [grafana](https://grafana.operate-first.cloud/login) and let me know if its fixed.

**Comment by Gkrumbach07** [comment]
> @Gkrumbach07 once https://github.com/operate-first/apps/pull/1593 gets merged try logging into [grafana](https://grafana.operate-first.cloud/login) and let me know if its fixed.

That fixed it. Thanks!
