### ISSUE TITLE
[moc/smaug] Install Operators needed for setting up opentelemetry tracing

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#1531]
The following operators need to be installed:

- [x] jaeger operator
- [x] otel-collector

Related https://github.com/operate-first/support/issues/401

**Comment by HumairAK** [comment]
operator installed, see: https://github.com/operate-first/apps/pull/1932 and https://github.com/operate-first/apps/pull/1933

**Comment by sallyom** [comment]
@HumairAK this issue is resolved w/ jaeger + opentelemetry collector running in smaug, should we close this now?

**Comment by SamoKopecky** [comment]
/remove-lifecycle stale 

Can this issue be closed @4n4nd, the operators are installed.

> operator installed, see: #1932 and #1933
