### ISSUE TITLE
[workload-overview] Test out using annotations/labels in namespace manifests to store and query project information for the dashboards

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#1661]
Test adding project information to namespace manifests (https://github.com/operate-first/apps/blob/master/cluster-scope/base/core/namespaces/opf-jupyterhub/namespace.yaml) and see if they can properly be displayed in a grafana dashboard

**Comment by bryanmontalvan** [comment]
What exactly type of annotations or labels would store in the manifests? (Project group/owner, description)?

**Comment by 4n4nd** [comment]
since labels are not very flexible, I think we should just write an exporter that exports annotations data as prometheus metrics.

**Comment by 4n4nd** [comment]
This was tested and we found that labels are not the best place to store metadata since the label values have very strict character limitations. We have decided to create an annotations exporter which will let us export k8s resource annotations as prometheus metrics ([New issue](https://github.com/operate-first/apps/issues/1717)).
