### ISSUE TITLE
List of Services / apps to which alerts are to be added

### ISSUE THREAD

**Issue by mubariskhan96** [operate-first/apps#1677]
I'm trying to set up alerts for apps within Operate First. In this issue I will go over the apps for which I will be setting up the Alerts. I will work on configuring the Alerts in the same order as I list them here. 

So, the tentative list of apps is: 

- [ ] Jupyter Hub 
- [ ] Kafka 
- [ ] seldon
- [ ] argocd
- [ ] Trino

If you want me to do them in a different order, then please let me know. Also, what are some other apps that you want to monitor or set the alerts for? The ones I listed above are from the moc/smaug cluster.

**Comment by HumairAK** [comment]
I'd remove `argo` from that list. I don't think we're even deploying it, and if we are, I don't think anyone is using it. 

argocd is a good one, but I'm not sure if we're exposing metrics for that

**Comment by mubariskhan96** [comment]
Thanks!  I will tentatively replace argo with argocd there and will investigate later if the metrics for it are being exposed

**Comment by ravitejamanepalli** [comment]
[[](https://github.com/SeldonIO/seldon-core/blob/master/doc/source/analytics/analytics.md
](url)

Requests from the service orchestrator to a component, e.g., a model
seldon_api_executor_client_requests_seconds_count    (bucket,count,sum) - histogram type metric
seldon_api_executor_client_requests_seconds_summary_(count,sum) - summary type metric

**Comment by durandom** [comment]
@mubariskhan96 @ravitejamanepalli can we close this issue? Looks like you've added a good set of alerts already.

/assign @mubariskhan96
