### ISSUE TITLE
Will Cluster Logger logging pick up our individual pod logs?

### ISSUE THREAD

**Issue by goern** [operate-first/apps#168]
If my pod is writing to stdout, something like `{"component":"hook","event-GUID":"ce0242c0-60d4-11eb-97f4-45029f1fcbd1","event-type":"issue_comment","external-plugin":"needs-rebase","file":"prow/hook/server.go:227","func":"k8s.io/test-infra/prow/hook.(*Server).demuxExternal.func1","level":"info","msg":"Dispatched event to external plugin","severity":"info","time":"2021-01-27T19:21:07Z"}` is it picked up by cluster logging and where and I find it?

/kind question
/sig documentation

**Comment by tumido** [comment]
yes it should be picked up by cluster logging. We're working on that bit here https://github.com/operate-first/apps/issues/171

**Comment by tumido** [comment]
I see - this issue calls for documentation, doesn't it? :slightly_smiling_face: In that case.. yes, we still have to document this.

**Comment by tumido** [comment]
FTR from the chat:

```
Marcel Hild
@Tom Coufal @Humair Khan do we have ocp monitoring installed in the CNV cluster? I.e. node-exporter and the default grafana dashboards

Tom Coufal
Yes it is. However it is not yet managed by operate-first. The namespace and the resources are in place, the access seems to be limited to cluster admins. I think this is comes from the initial install/setup by @Lars Kellogg-Stedman  we didn't yet fully got to that bit.

Tom Coufal
alertmanager-main-openshift-monitoring.apps.cnv.massopen.cloud
grafana-openshift-monitoring.apps.cnv.massopen.cloud
prometheus-k8s-openshift-monitoring.apps.cnv.massopen.cloud
thanos-querier-openshift-monitoring.apps.cnv.massopen.cloud
I'm getting forbidden myself on those routes, but they exist
```
we need to resolve the permissions by aggregating our rbac to that namespace similar to this:
https://github.com/operate-first/apps/blob/master/cluster-scope/base/namespaces/openshift-monitoring/kustomization.yaml

I'll follow up in a PR on that.

**Comment by tumido** [comment]
@goern you should be able to track down your logs at  https://kibana-openshift-logging.apps.cnv.massopen.cloud/ for example. Does that work for you or you'd prefer Loki?

We need some consolidation on all of this metrics/monitoring. I'll start another issue for that.

**Comment by tumido** [comment]
@goern I'm actually confused here more and more... What is the initial ask? Like.... where do I find traces from my particular app? That should be covered by Observatorium and Loki, correct @4n4nd?

I also know this would be consumed from the Cluster Logging as well, so you should be able to view it at the `openshift-logging` [Kibana](https://kibana-openshift-logging.apps.cnv.massopen.cloud/)

**Comment by HumairAK** [comment]
I understood the question to mean that how can users (of any namespace) see their pod logs in kibana, similar to how IDH has it setup.

**Comment by 4n4nd** [comment]
I am a little confused too because there are two different things being talked about here:
1. ocp monitoring, which is mostly metrics
2. original question from @goern is about being able to query logs from the CLO

for 1, we have all the cluster metrics available in [operatefirst prometheus](http://prometheus-portal-opf-monitoring.apps.cnv.massopen.cloud/graph)
for 2, I think @tumido is trying to figure out the minimum rbac need for a user to view their logs and once he is able to do that you should be able to query logs for your pods using [kibana](https://kibana-openshift-logging.apps.cnv.massopen.cloud/)

**Comment by HumairAK** [comment]
yes I think the original question refers to your point no.2, and I think @tumido  has already answered it. With regards to rbac and permissions, we have issues already for that open, so I think we can close this issue and talk there (see #194)

**Comment by 4n4nd** [comment]
@goern I just tested this and you should be able to query the logs for pods that you have access to using [kibana](https://kibana-openshift-logging.apps.cnv.massopen.cloud/)
