### ISSUE TITLE
Create a declarative way for importing clusters via acm

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1699]
The current workflow for adding a cluster to the operate-first cloud is to first run a manual step of importing it via the UI. However, the procedure [here](https://cloud.redhat.com/blog/bring-your-own-fleet-with-red-hat-advanced-cluster-management-for-kubernetes-auto-import-and-automation-tools) , outlines a way one can do this declaratively. Seems like you just create a namespace, secret, managedcluster, klusteraddonconfig, and acm does the rest. We should bring this into part of our work flow and follow a similar process. 

Relevant links: 
ACM manifests: https://github.com/operate-first/apps/tree/master/acm 
Operate First ACM Docs: https://www.operate-first.cloud/apps/content/acm/README.html

**Comment by durandom** [comment]
since we don't onboard clusters on a daily basis, I think we can close this for now.
@larsks IIRC you were looking into something similar for NERC. If you implemented a solution, could you link that here?

/assign @HumairAK 
/close
