### ISSUE TITLE
Enable monitoring for Superset

### ISSUE THREAD

**Issue by anishasthana** [operate-first/apps#17]
Related: #11

**Comment by HumairAK** [comment]
The strategy has evolved a bit, we'll be using one service monitor for monitoring odh components, see [here](https://github.com/operate-first/apps/pull/123/files) and [the adr here](https://github.com/operate-first/blueprint/blob/main/docs/adr/0006-monitoring-structure.md) for more info.

**Comment by HumairAK** [comment]
Re-opening, I think we still need an issue for monitoring being enabled for superset, so this is sufficient.

**Comment by HumairAK** [comment]
bump
