### ISSUE TITLE
Request access to smaug namespaces

### ISSUE THREAD

**Issue by mayaCostantini** [operate-first/apps#1703]
As a member of the `thoth-devops` group, I would like to have access to the following namespaces in smaug:

- openshift-pipelines
- opf-pulp
- thoth-middletier-prod
- thoth-backend-prod
- thoth-frontend-prod
- thoth-bots-prod
- thoth-amun-inspection-prod
- thoth-infra-prod
- thoth-amun-api-prod
- opf-ci-prow
- tekton-chains
- opf-ci-pipelines

**Comment by HumairAK** [comment]
@mayaCostantini can you add your github handle to [this group](https://github.com/operate-first/apps/blob/master/cluster-scope/base/user.openshift.io/groups/thoth-devops/group.yaml) and submit a PR?

**Comment by mayaCostantini** [comment]
Sure, thanks @HumairAK

**Comment by HumairAK** [comment]
@mayaCostantini can this be closed now?

**Comment by mayaCostantini** [comment]
Yes, thanks for the help!

**Comment by mayaCostantini** [comment]
@HumairAK I get an authentication error when trying to access the OpenShift console after you reinitialized y access yesterday. Do you mind if I keep this issue open until I can get access  to the namespaces?
