### ISSUE TITLE
Cluster Logging RBAC to be able to view cluster logs on kibana

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#171]
We need to figure out what kind of RBAC is required for a user to be able to view logs in [kibana](https://kibana-openshift-logging.apps.cnv.massopen.cloud/)

I am able to create indexes and see logs as an admin of the `openshift-logging` namespace, but @eranra was not able to see the logs with `view` privileges to the namespace

**Comment by eranra** [comment]
Once we get that working, need to assign those credentials to the entire team under `open-aiops`.

@drbwa @durandom @tumido
