### ISSUE TITLE
Elyra notebooks for OS-Climate do have GPU selector but not memory size selector

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [operate-first/apps#1748]
In a previous incarnation, it was possible to select RAM size for Elyra notebooks (from 4GB to 32GB I believe).  And while it is possible to select whether the notebook uses a single GPU or no GPU, it is not possible to select RAM size, which is problematic for loading PUDL data (which momentarily needs lots of ram to process a 3.9GB tarfile that sits within a 6.5GB tgz file).  When the tarfile is skipped, the notebook can complete.  But when it is not skipped, the notebook is killed due to OOM.

Can we please have either 4GB, 8GB, 16GB, 32GB (S, M, L, XL) or 4GB, 16GB, 64GB (S, M, L) as selections?

**Comment by Shreyanand** [comment]
Faced the same issue, screenshot attached.
![Screenshot from 2022-03-18 14-22-34](https://user-images.githubusercontent.com/8916126/159062478-29147d50-3fa4-4d6f-be6c-49adfc6b41e6.png)

**Comment by erikerlandson** [comment]
Here is how it was done on CL1
https://github.com/operate-first/apps/pull/1061

**Comment by MichaelTiemannOSC** [comment]
Bump!

**Comment by MichaelTiemannOSC** [comment]
Whatever fix was implemented, it is just not working.  I consider it unacceptable that the RAM size selector is not immediately available with the GPU size selector.  I waste minutes of time every time I have to restart my JupyterHub server, poking at random options, refreshing, starting and stopping until, seemingly at random, I finally get the size selection option.  It should be available from the very start, and should simply work.

This is the URL from which I'm getting unreliable results: https://jupyterhub-odh-jupyterhub.apps.odh-cl2.apps.os-climate.org/hub/spawn

**Comment by joemoorhouse** [comment]
Hi, +1 for me on request for a fix please. I'm finding the same thing and struggling to get an instance > 2GB memory currently. Strangely enough this has just started happening for me.
Thanks,
Joe

**Comment by MichaelTiemannOSC** [comment]
Using JavaScript console we see two problems: a 404 when attempting to access the sizing API, and no return for the default size of Small.

![Screen Shot 2022-04-27 at 8 59 35 AM](https://user-images.githubusercontent.com/72577720/165523695-cb42c377-d838-4f7a-9ef5-f22ca9453be1.png)
