### ISSUE TITLE
Onboard Morty cluster to Operate-First monitoring

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#1752]
Part of https://github.com/operate-first/apps/issues/1471

- [ ] Add a grafana datasource in operate-first smaug grafana to be able to query metrics from morty cluster monitoring prometheuses
- [ ] Configure Morty cluster monitoring prometheus instance to remote write metrics into operate-first Thanos instance in Smaug
- [ ] Configure Morty user-workload-monitoring prometheus instance to remote write metrics into operate-first Thanos instance in Smaug

**Comment by harshad16** [comment]
/remove-lifecycle stale
/triage accepted

we would take this one to learn the process of monitoring.

**Comment by Gregory-Pereira** [comment]
Are we still doing this as we will be decommissioning the `Morty` cluster in 3 weeks?

**Comment by HumairAK** [comment]
Nope! closing
