### ISSUE TITLE
Suggestion about Inexact information on the GitOps Docs Getting Started page

### ISSUE THREAD

**Issue by carlosGimeno** [operate-first/apps#1766]
## Inexact information on the Getting Started page of the GitOps Documentation

In the section ["There are 3 parts to Operating First"](https://www.operate-first.cloud/apps/content/about/intro.html#there-are-3-parts-to-operating-first), the third point states that "The Mass Open Cloud (MOC) is a production cloud resource where projects are run.". While it remains somewhat true since smaug within MOC is the cluster for almost all user workloads, I think it seems outdated to just mention MOC and not the rest of the clusters (some of these also run experimental workloads) in this explanation/description of what Operate First is.

**Comment by carlosGimeno** [comment]
kind/documentation

**Comment by SamoKopecky** [comment]
@carlosGimeno Is this issue still valid?

If it is, is this a valid suggestion @HumairAK?

**Comment by HumairAK** [comment]
I think this doc is a bit too outdated, and not sure if it's worth trying to reconcile it. I also don't think anyone looks at it. I vote we remove this for now until we get a chance to properly assess the state of the docs and how we want to move forward with it.

**Comment by SamoKopecky** [comment]
I agree with that, going to create a PR to remove it.
