### ISSUE TITLE
Enable monitoring for the Data Catalog

### ISSUE THREAD

**Issue by anishasthana** [operate-first/apps#18]
Related: #11 
This should probably be split into separate issues for the individual data catalog components

**Comment by tumido** [comment]
I'll cover it once the real life data catalog deployment is available.

**Comment by HumairAK** [comment]
The strategy has evolved a bit, we'll be using one service monitor for monitoring odh components, see [here](https://github.com/operate-first/apps/pull/123/files) and [the adr here](https://github.com/operate-first/blueprint/blob/main/docs/adr/0006-monitoring-structure.md) for more info. I've updated the title to reflect this change.
