### ISSUE TITLE
Enable PVCs in infra cluster

### ISSUE THREAD

**Issue by dystewart** [operate-first/apps#1844]
In order to complete the vault deployment in the infra cluster, we need to set up PVCs on the infra cluster. Perhaps enable local storage on the cluster? 
@larsks @HumairAK

**Comment by HumairAK** [comment]
@larsks made request to nese folks, have not heard back yet 

options: 
1. move to smaug as short term solution 
2. There is another storage driver for k8s called longhorn, gives volume storage using local volumes

**Comment by SamoKopecky** [comment]
@larsks @HumairAK Have we decided on the next step here?

> 



> @larsks made request to nese folks, have not heard back yet
> 
> options:
> 
>     1. move to smaug as short term solution
> 
>     2. There is another storage driver for k8s called longhorn, gives volume storage using local volumes

**Comment by tumido** [comment]
Infra has PVCs now via ODF (data stored at NESE), closing as resolved.
