### ISSUE TITLE
As an OPF SRE, I would like to be able to assign different users/quota for the same namespaces located on different clusters, so that I have more incentive to re-use namespaces across clusters.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1849]
### Additional Context: 
Current situation: 
- Namespaces/Groups are found in base directory 
- Namespace rbac/quotas and Group userlist are thus found in the base directory 
- The direct implication of this is that whenever the same namespace is duplicated across clusters it will always have the same quota, and the groups will have the same users. 

Problem: 
- Not all namespaces in all clusters are equivalent, e.g. ODH on os-cl2 may not require same quota as odh and smaug. Also odh-admin ocp group on Smaug may not be the same as on osc-cl2.

### Acceptance Criteria

- [ ] Should be able to have the same namespace on different clusters (pulled from base) with the added ability to have different members given access to these namespaces
- [ ] OPF CLI should reflect this change 
- [ ] Documentation should be updated

**Comment by larsks** [comment]
Previously discussed, and I continue to be in favor of making quotas (and probably even groups) a per-cluster configuration (or in cases where we explicitly want to share the config across clusters make use of some sort of `common` directory).

**Comment by SamoKopecky** [comment]
/remove-lifecycle stale

@HumairAK Are we still going with this or are making quotas and groups a per-cluster thing?

> Previously discussed, and I continue to be in favor of making quotas (and probably even groups) a per-cluster configuration (or in cases where we explicitly want to share the config across clusters make use of some sort of `common` directory).
