### ISSUE TITLE
Proposal to deploy Stackrox on Operate First/Smaug

### ISSUE THREAD

**Issue by carlosGimeno** [operate-first/apps#1876]
# Context/Introduction
As part of my Co-op project, I am focusing on enhancing security monitoring in Operate First. One of the key actions of this is curating and deploying tools that would focus on this area. For the past months I was focused on researching, adapting and preparing a proposal that might seem acceptable for installing such software. In this sense, I was working on a proposal to deploying kube-bench, a vulnerability analysis tool which I have been testing locally for one and a half months. However, last week I discovered Stackrox, a more complete open-source tool that looks very promising which [was acquired by Red Hat in 2021 and released as open-source in late March](https://www.stackrox.io/blog/open-source-stackrox-is-now-available/). 

# Stackrox

Stackrox is the open-source version of RHACS (Red Hat Advanced Cluster Security for Kubernetes). It is a very-complete suite that focuses on strengthening the security of Kubernetes clusters. It does this in many aspects: Vulnerability Analysis, RBAC enforcement, establishing security policies, security compliance analysis,..

# Proposal / The Plan

The end goal would be to try to deploy and integrate Stackrox into Operate First. By integrating, I am hoping to integrate all metrics, logs and alerts potentially produced by this tool into the current apps/tools deployed in Operate First clusters (loki for logs, prometheus for alerts, grafana for visualizing metrics + logs + alerts,...). However, before deploying Stackrox, I am going to test it locally in order to fully understand how it works among other steps outlined in the checklist below. Additionally, I would significantly appreciate any feedback/concerns/suggestions regarding this proposal. 

- [X] Research on Stackrox
- [ ] Locally Testing Functionality + Performance 
- [ ] Locally Testing Integrations 
- [ ] Ready for Deployment in Smaug
- [ ] Deployed 

# More Information

- [Stackrox Repo](https://github.com/stackrox/stackrox) 
- [Stackrox Website](https://www.stackrox.io/)
- [Stackrox Docs](https://www.stackrox.io/docs/)

**Comment by HumairAK** [comment]
@carlosGimeno this sounds great, is this something you'd be willing to discuss / present in sig-operations bi-weekly meeting?

**Comment by HumairAK** [comment]
@carlosGimeno I see you added a thumbs up -- can you update one of the agenda items here: https://docs.google.com/document/d/1uEcLGP_sBSNwTLPOo_2Nu6oTqPytOTBt0c0_pVUQJwo/edit# whichever date works for you

**Comment by durandom** [comment]
@traytorous is https://github.com/operate-first/apps/pull/2211 part of this issue?

**Comment by traytorous** [comment]
@durandom Yes :)

**Comment by Gregory-Pereira** [comment]
bump @carlosGimeno, we are about to deploy stackrox on smaug in the PR Marcel linked (#2211) as well as the argocd changes #2203 . If any work went into these two actions items (see below), it would be nice to add it soon
> - [ ] Locally Testing Functionality + Performance
> - [ ] Locally Testing Integrations

**Comment by traytorous** [comment]
@durandom Carlos doesn't work here anymore. I took over the project. I'll update the check list accordingly

**Comment by durandom** [comment]
I think we can close this issue in favor of https://github.com/operate-first/support/issues/614

**Comment by durandom** [comment]
feel free to re-open if needed
