### ISSUE TITLE
Update Argo Monitoring for ODH

### ISSUE THREAD

**Issue by anishasthana** [operate-first/apps#19]
Related: #11 

Upstream ODH already has prometheus monitors in place for Argo, but they haven't been updated in a long time. It's very possible that they don't correctly function any more / don't correctly grab metrics

**Comment by tumido** [comment]
I'll check that out, thanks!

**Comment by HumairAK** [comment]
The strategy has evolved a bit, we'll be using one service monitor for monitoring odh components, see [here](https://github.com/operate-first/apps/pull/123/files) and [the adr here](https://github.com/operate-first/blueprint/blob/main/docs/adr/0006-monitoring-structure.md) for more info.
