### ISSUE TITLE
Consolidation for logging and monitoring facilities

### ISSUE THREAD

**Issue by tumido** [operate-first/apps#193]
Right now we have too many logging/monitoring facilities and it's confusing for users, since we provide insufficient guidance on how to access/view their traces and which ever systems are even available for the users. I've started collecting some links and resources, feel free to chip in your findings.

| Namespace       | Applications     | Scope       | Required permissions  |
| --- | --- | --- | --- |
| `openshift-monitoring` | [Prometheus](https://prometheus-k8s-openshift-monitoring.apps.cnv.massopen.cloud), [Grafana](https://grafana-openshift-monitoring.apps.cnv.massopen.cloud), [AlertManager](https://alertmanager-main-openshift-monitoring.apps.cnv.massopen.cloud)  | Cluster | Minimal is `cluster-monitoring-view` cluster role |
| `openshift-logging`    | ElasticSearch, FluentD, [Kibana](https://kibana-openshift-logging.apps.cnv.massopen.cloud/) | Cluster | Minimal is read on `pods/log` for applications, `cluster-reader` for OpenShift resources |
| `opf-observatorium`    | [Grafana](https://grafana-route-opf-observatorium.apps.cnv.massopen.cloud/), Loki | Selected namespaces | Public |
| `opf-monitoring`       | [Prometheus](http://prometheus-portal-opf-monitoring.apps.cnv.massopen.cloud/), [AlertManager](http://alert-manager-opf-monitoring.apps.cnv.massopen.cloud/), [Grafana](https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/) | Selected namespaces | Public |

I'm getting a bit lost in what app deployment has what purpose, so we need to properly document which app should be accessed/used for which purpose and when to interact with each..

/sig documentation

Related: https://github.com/operate-first/apps/issues/168 https://github.com/operate-first/apps/issues/171

**Comment by tumido** [comment]
cc @hemajv @4n4nd @HumairAK

**Comment by 4n4nd** [comment]
@tumido as far as I know, to access `opf-monitoring`/`opf-observatoium` components you don't need any special roles and everything is open.

For `openshift-monitoring`, I think you need [`cluster-monitoring-view`](https://github.com/operate-first/apps/blob/master/cluster-scope/base/clusterrolebindings/metrics/cluster-metrics-federation-clusterrolebinding.yaml#L9) to be able to access the metrics.

**Comment by anishasthana** [comment]
openshift-monitoring is an "official" namespace right? it's provisioned when the cluster is initially created and has no input from us.

**Comment by tumido** [comment]
> @tumido as far as I know, to access opf-monitoring/opf-observatoium components you don't need any special roles and everything is open.

So even if I don't have any credentials I can view the metrics from all the apps funneled to those? Just asking, honestly I'm getting completely lost in all those permissions and things...

**Comment by 4n4nd** [comment]
> etely lost in all those permissions and things...

Yes exactly, as long you have the endpoints, all the metrics are available for anyone to see.

**Comment by tumido** [comment]
> openshift-monitoring is an "official" namespace right? it's provisioned when the cluster is initially created and has no input from us. iirc this is where cluster monitoring metrics are scraped and all that, so I think the average user wouldn't care about it.

@anishasthana we may have projects interested in cluster scoped metrics for analysis data etc... I'd rather keep track of what access level is needed for what so we can reference in in the time of need. :slightly_smiling_face:

**Comment by 4n4nd** [comment]
> > openshift-monitoring is an "official" namespace right? it's provisioned when the cluster is initially created and has no input from us. iirc this is where cluster monitoring metrics are scraped and all that, so I think the average user wouldn't care about it.
> 
> @anishasthana we may have projects interested in cluster scoped metrics for analysis data etc... I'd rather keep track of what access level is needed for what so we can reference in in the time of need. slightly_smiling_face

@tumido all cluster metrics are public using the `opf-monitoring` Prometheus, so we don't need to give access to the `openshift-monitoring` namespace to anyone.

**Comment by tumido** [comment]
/remove-lifecycle stale

/assign @4n4nd

@4n4nd can you please comment on this and either close or define some acceptance criteria for this issue, please?
