### ISSUE TITLE
CRD extensions.dashboard.tekton.dev is part of applications cluster-resources-smaug and default

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1936]
Argocd thinks a resource is part of an ArgoCD if it has this label: 

`app.kubernetes.io/instance: <app-name>` 

The crd resource extensions.dashboard.tekton.dev has this label: 

`app.kubernetes.io/instance: default` 

But we have it as part of [this app](https://argocd.operate-first.cloud/applications/cluster-resources-smaug).
Because we add it [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/moc/smaug/kustomization.yaml#L15). 

I.e. ArgoCD wants to add this label: 

`app.kubernetes.io/instance: cluster-resources-smaug`

But it sees the label above, so it reports: 
```
CustomResourceDefinition/extensions.dashboard.tekton.dev is part of applications cluster-resources-smaug and default
```

We don't have an argocd application called `default`. 

My guess is, this resource is being deployed by something else, and if we really do need to be deploying it via `cluster-scope`.

**Comment by HumairAK** [comment]
@harshad16 any updates ?

**Comment by harshad16** [comment]
i will get this in soon 
was caught up with other work.

**Comment by harshad16** [comment]
The resource is not being installed by any other app.
The CRD itself was added in the repo with label `app.kubernetes.io/instance: default` which is checked by agrocd for instance duplication.
