### ISSUE TITLE
opf-kafka-smaug argocd app out of sync and in degraded state

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1952]
See here: https://argocd.operate-first.cloud/applications/opf-kafka-smaug?resource=sync%3AOutOfSync

https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-kafka/pods 

odh-message-bus-kafka-3 on crashloop, maybe that's why?

**Comment by SamoKopecky** [comment]
/remove-lifecycle stale

`odh-message-bus-kafka-3` is not crashing, but the app is still out of sync.

**Comment by harshad16** [comment]
opf-kafka-smaug is fixed and syncs properly now
https://argocd.operate-first.cloud/applications/opf-kafka-smaug?conditions=false&operation=false&resource=
thanks, everyone for their efforts.

closing the issue.
