### ISSUE TITLE
Bring OSC clusters under operate-first auth

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1953]
ATM provisioning access to OSC clusters requires: 
- must be an OSC [github org member](https://github.com/os-climate)   (Only org owners seem to be able to hand out this access?)
- must be in the OSC github org team: `odh-env-users` : https://github.com/orgs/os-climate/teams/odh-env-users

Note that access to actual services on the cluster is further gated by OCP rbac restrictions. E.g. you cannot use odh superset unless you are in the appropriate OCP group.

We can create a new authrealm for identitatem that allows for this.

### Acceptance criteria: 

- [ ] OSC-CL1 and OSC-CL2 are configured using identitatem
- [ ] Authentication conforms to requirements (i.e. invite into osc and team odh-env-users is required).

**Comment by SamoKopecky** [comment]
@HumairAK Are we still planing to work on this?
