### ISSUE TITLE
Install new OCP cluster on the Community Cage at RDU2

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1956]
We now have ~14 1U servers in the RDU2 Community Cage. 

They are waiting on their DNS names to be decided, with the proposal  server[1-14].rdu2.operate-first.cloud. 

Once done I believe we'll be ready to install OCP on those machines.

**Comment by SamoKopecky** [comment]
/remove-lifecycle stale

@HumairAK Are we still waiting for the DNS names to be decided?

**Comment by HumairAK** [comment]
from the ticket: 
> This is waiting on NOC to create the vlan, before we can setup anything.
