### ISSUE TITLE
Re-evaluate need for approved-users group

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#197]
From what I understand, the [approved-users group](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/groups/approved-users.enc.yaml#L4) allows folks to create namespaces manually, we want to remove this capability so that namespaces are only created via git -> argocd. So we should consider removing or limiting access to this group. Thoughts?

**Comment by tumido** [comment]
cc @larsks @anishasthana @4n4nd

**Comment by tumido** [comment]
Thoughts: yes, I agree!

**Comment by anishasthana** [comment]
Agreed

**Comment by larsks** [comment]
Right, that's the plan we've discussed. If we have a workflow in place to manage projects and permissions, we no longer need the `approved-users` group.

**Comment by HumairAK** [comment]
@larsks can this group be simply removed? (I'm not sure if it's being used in any other way), or should I just empty out the users in that list?

**Comment by larsks** [comment]
The group can simply be removed. There are some clusterrolebindings associated with it that should be removed as well, unless openshift will remove those for us when the group is deleted.

**Comment by 4n4nd** [comment]
yeah let's remove this group :+1:

**Comment by HumairAK** [comment]
Group was removed, closing.
