### ISSUE TITLE
Smaug machines stuck on Provisioned

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1979]
We have 2 machines on smaug stuck on provisioned state:

```
~ $ oc -n openshift-machine-api get machine | grep Provisioned
smaug-dq8j2-worker-0-4c66k   Provisioned                          266d
smaug-dq8j2-worker-0-6gk2s   Provisioned                          266d
```

resulting in:
https://console-openshift-console.apps.smaug.na.operate-first.cloud/monitoring/alerts?rowFilter-alert-state=firing&rowFilter-alert-source=platform&resource-list-text=machine

closest thing I found for a workaround was: https://access.redhat.com/solutions/5297401 but this seems to be talking about vms

**Comment by HumairAK** [comment]
@rbo

**Comment by rbo** [comment]
Here an example of how to create an iso that's boots install and try to join the cluster:
```
$ ./coreos-installer iso customize --dest-device /dev/sda --dest-ignition ~/fcos/user.ign -o rhcos-4.10.3-x86_64-nelson-3.x86_64.iso rhcos-4.10.3-x86_64-live.x86_64.iso
Boot media will automatically install to /dev/sda without confirmation.
$ ./coreos-installer iso ignition show rhcos-4.10.3-x86_64-nelson-3.x86_64.iso
{"ignition":{"version":"3.3.0"},...
```

**Comment by HumairAK** [comment]
Will try to ssh into these stuck nodes and rebooting them first

**Comment by HumairAK** [comment]
/remove-lifecycle stale 

we had @naved001 reboot these machines, and the nodes spawned again but they dont' seem to be showing the corresponding machines, nor do the machines show the correponding nodes: 

![image](https://user-images.githubusercontent.com/10904967/193639920-00857666-d019-47b1-8abd-c434dc4cc184.png)

![image](https://user-images.githubusercontent.com/10904967/193639987-6e43122e-a63f-478d-8c76-edb34f2b65ed.png)


but the nodes are scheduling pods :man_shrugging:

**Comment by rbo** [comment]
All CSR Approved? It's worth it to double-check, even with machine sets.

**Comment by tumido** [comment]
Yes, there are no CSRs present.

**Comment by rbo** [comment]
puh I don't know. I had this problem last time on AWS too, but now time to debug.  I can only suggest we'll take an hour and look at it together.
