### ISSUE TITLE
Contributor docs

### ISSUE THREAD

**Issue by tumido** [operate-first/apps#198]
Provide a contributors doc, so it is known what standards we aim to enforce.

> Can you please provide a contributor doc specifying this for this project? Because as I mention it is a personal decision and we could discuss for some time about pros/cons but in this case, I'm a contributor here so I ll squash them, but maybe a PR template specifying this might help others from the beginning :) Thanks!

_Originally posted by @pacospace in https://github.com/operate-first/apps/pull/191#issuecomment-771453743_

**Comment by HumairAK** [comment]
hrmm this hsould have been closed, fixed in #222
