### ISSUE TITLE
Create backup of Vault & Migrate Vault server to Infra cluster

### ISSUE THREAD

**Issue by dystewart** [operate-first/apps#1997]
Once #1844 is resolved, we will be moving Hashicorp Vault from the Smaug cluster to the infra cluster. 

In order to do this we will need to create a snapshot of vault: [https://learn.hashicorp.com/tutorials/vault/sop-backup](https://learn.hashicorp.com/tutorials/vault/sop-backup)

Then we should be able to restore the state in the infra cluster with this snapshot using: [https://learn.hashicorp.com/tutorials/vault/sop-restore](https://learn.hashicorp.com/tutorials/vault/sop-restore)

**Comment by SamoKopecky** [comment]
/remove-lifecycle stale

Waiting on #1844 to be closed.

**Comment by tumido** [comment]
/cc @durandom

I think we were talking about part of this recently

/remove-lifecycle rotten
