### ISSUE TITLE
Python 3.6 too old for pandas, pint, etc.

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [operate-first/apps#2009]
This concerns the Jupyter Notebook options presented to the user when starting an OS-Climate JupyterLab startup screen (probably somewhere around here: https://github.com/operate-first/apps/tree/master/kfdefs/overlays/osc/osc-cl2/jupyterhub).

We debugged that a simple notebook creating a pandas dataframe containing Pint quantities was not working because the Python version offered by the Minimal Python notebook (version 3.6) is just too old.  A less ancient Python 3.8 coming from Custom Elyra Notebook did work.

The minimal Python notebook configuration should be upgraded to at least version 3.8 or should be retired and not visible, lest users mistakenly select an environment that cannot run modern Python workloads.

@erikerlandson

**Comment by MichaelTiemannOSC** [comment]
The latest spawn window on CL2 no longer advertises Py3.6.

**Comment by MichaelTiemannOSC** [comment]
My bad: `Minimal Python Python v3.6.8` is still there...it just moved from the bottom of the first column to the top of the 2nd column.  Offering Python 3.6 is just asking for trouble.

**Comment by MichaelTiemannOSC** [comment]
This is the file that should be updated to offering a more modern version of Python: https://github.com/operate-first/apps/blob/master/kfdefs/base/jupyterhub/notebook-images/s2i-spark3.0.1-minimal-notebook.yaml

**Comment by durandom** [comment]
@erikerlandson @MichaelClifford  if this is also affecting the os-climate clusters and is a problem, would you be able to take care of this?

/assign @erikerlandson

**Comment by MichaelTiemannOSC** [comment]
Thanks for the touch, Marcel!  I should add that there are definitely a set of libraries that I think are "minimal" for the OS-Climate world.  It takes me about 60 seconds to `pipenv install` them when I start a fresh notebook, a minute of my life I cannot get back every day!  Here's my current list, but we really should sync with @caldeirav to see if there are some others that really make sense to put into a base image.

```
[packages]
src = {editable = true, path = "./"}
awscli = "*"
python_dotenv = "*"
numpy = "*"
pandas = "*"
pyarrow = "*"
boto3 = "*"
osc-ingest-tools = "*"
openpyxl = "*"
Pint = "*"
Pint-Pandas = "*"
pandas-profiling = "*"
openscm-units = "*"
grpcio-health-checking = "==1.48.2"
python-pachyderm = "*"
```
