### ISSUE TITLE
Open Infra Summit Demo on Operate First

### ISSUE THREAD

**Issue by oindrillac** [operate-first/apps#2014]
@aakankshaduggal and I presenting a demo at Open Infra Summit in 2 weeks which showcases the Operate First community cloud and services. We plan to use the following services on Operate First for our demo:

- Kubeflow pipelines on osc-cl2
- opf-datacatalog bucket
- JupyterHub on smaug
- Trino on smaug
- Cloudbeaver on smaug
- Superset on smaug

I see there's an outage until May 26th. Will the services be back up after that? And is there any other planned outage afterwards?

**Comment by HumairAK** [comment]
> Will the services be back up after that? 

This is the plan yes. 

> And is there any other planned outage afterwards?

Nope there is not. 


> Kubeflow pipelines on osc-cl2

Is this something that's needed on smaug? I ask since everything else seems to be on smaug. We have an instance there we can fix up (this was blocked previously due to an ocp upgrade that has since been resolved) ?

**Comment by oindrillac** [comment]
Thanks for the response @HumairAK! Sorry, I didn't realize I opened this on the apps repo. 😱  I am assuming support would have been a better location.

> Is this something that's needed on smaug?
Not necessarily. If we can get a different bucket to work with the kfp on cl2, that would also work. Currently, just facing some issues with getting kfp to run succesfully on cl2. We can get the rest of the demo using services on smaug when its back up next week.

**Comment by HumairAK** [comment]
@oindrillac as the demo is done, this can be closed now yes?

**Comment by HumairAK** [comment]
Closing, please re-open if there's more to do here.
