### ISSUE TITLE
Deploy backstage on smaug cluster

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2036]
After investigating backstage (see [here](https://github.com/operate-first/support/issues/578)), we are now confirmed with going ahead with this as our service catalog solution. 

Let's start with deploying backstage onto the smaug cluster. As an initial step, read-only mode is sufficient. And we can iterate on it.

**Comment by SamoKopecky** [comment]
Service is deployed at service-catalog.operate-first.cloud/
