### ISSUE TITLE
Grafana app in smaug not syncing correctly

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2054]
App link: https://argocd.operate-first.cloud/applications/grafana-smaug

Note the change: 

```
    serviceAccount:
      labels:
        app.kubernetes.io/instance: cluster-resources-smaug
```

When sync'd, this change fails to apply (or is being overwritten). Turning on auto sync for this app thus results in an infinite sync loop. 

## Acceptance criteria: 
- [x] Grafana app should sync correctly

**Comment by harshad16** [comment]
sync is working well now.
