### ISSUE TITLE
Remove ODH operator via OLM and use deployment instead 

### ISSUE THREAD

**Issue by tumido** [operate-first/apps#206]
^ That is a provocative title

Resolve https://github.com/opendatahub-io/opendatahub-operator/issues/85 https://github.com/operate-first/apps/issues/167

and deploy the operator manually similar to Observatorium

**Comment by tumido** [comment]
we need a way to prevent users from creating `kfdef`s and deploying resources with a cluster-admin permissions. This might be the right way, since it would allow us to manually define the `kfdef` aggregate cluster roles.

**Comment by HumairAK** [comment]
We have discussed at length about this, and the security gap here is rather large, we cannot simply allow the current situation to exist whereby a project admin can effectively takeover the cluster. Some ideas to get around this (both require removing odh operator from olm and manualy deploying the csv that's been limited in some scope): 

Option 1: Convert ODH to a namespace scoped installation
I'm not sure whether this would work, but my understanding is that the things that would change are simply the rbac rules that are created for the operator's visibility of other namespaces, and the users visibility of the operators. We would have an odh operator for every kfdef in each namespace, and these namespaces would be restricted to admins only. 

Option 2: Limit the RBAC access of the ODH operator itself
The implications of this are a bit more significant I think. This essentially means limiting ODH's cluster-admin access, and not allow ODH to install things like operators, crds, clusterroles, clusterrolebindings, etc. This would mean we do not use ODH to provision Prometheus Operator, Grafana Operator, and Strimz. We would use argocd and our operator management framework as introduced in [this adr here](https://github.com/operate-first/blueprint/blob/main/docs/adr/0011-operators.md). 

Open to other suggestions !

**Comment by HumairAK** [comment]
@durandom @vpavlin

**Comment by HumairAK** [comment]
Option 3:
Another option would be to just install ODH on a separate cluster and allow only cluster admins direct access to the cluster, then hand out the links to the services only. AFAIK this is how managed odh is planning on doing it.

**Comment by tumido** [comment]
Option 4: Limit the `kfdef` rbac
Currently the OLM framework doesn't allow to limit the aggregation rules on CRDs, when the operator is deployed as cluster scope. Converting ODH operator OperatorHub (OLM) install to a "manual" install via specifying our own `CRD`, `ClusterRole`s and `Deployment` would allow us to control which users have access to `kfdef` CR. Therefore only certain roles (read as "only `cluster-admin`") would be allowed to create `kfdef`.

**Comment by HumairAK** [comment]
Option 4: 
Install ODH on its own cluster, allow only cluster-admins access to the cluster namespaces, console, etc. Users interact with only odh service links, but cannot use this cluster to create/use their own namespaces. @anishasthana  ?

**Comment by anishasthana** [comment]
We sort of did option 4 internally too, so that's a workaround. Couldn't we also do some rbac business to block the average user from accessing/creating kfdefs?

**Comment by tumido** [comment]
@anishasthana only via options 1 or 3. Openshift RBAC is purely additive, and the aggregate roles are created by OLM - there's no way to restrict that.

**Comment by HumairAK** [comment]
So far I'm leaning towards option 3, as that feels like the one to cause the least issues.

**Comment by vpavlin** [comment]
@lavlas Any thoughts on how to limit who/where can KFDef be deployed without throwing out OLM?

If that is not possible (and it probably is not), I guess option 3 makes sense for your use case.

It feels like using different installMode than `allNamespaces` might be helpful here?

**Comment by HumairAK** [comment]
Hey @vpavlin 

> It feels like using different installMode than allNamespaces might be helpful here?

I think that would fall under Option 1.

**Comment by LaVLaS** [comment]
OLM is restricting all operators to `allNamespaces` or `singleNamespace`. So you can no longer selectively choose which namespaces ODH can watch.

Option 3 is the best option since OLM is a blocker for your entire use case. Specifying the RBAC permissions via OLM (using a ClusterServiceVersion) requires that you explicitly define all of the possible permissions for an operator deployment even if some of those permissions will never be used based on the chosen ODH components.  Since you want to control the CRUD access of the operator, it appears that manually creating the `Deployment` and explicitly specifying the required permissions sounds like your best option.

**Comment by HumairAK** [comment]
@LaVLaS @vpavlin 

We would like to proceed with managing ODH via manual deployments rather than using OLM (Option 3 above). Is there a specific location where these manifests are stored that we can deploy manually?

I've checked [here](https://github.com/opendatahub-io/opendatahub-operator/tree/master/kustomize/overlays/opendatahub) but this seems to be outdated, as the image is different from the one found [here](https://github.com/operator-framework/community-operators/blob/85ff8bf1e63b5398a94774a8ee839d61f7a02aca/community-operators/opendatahub-operator/1.0.0/manifests/opendatahub-operator.v1.0.0.clusterserviceversion.yaml#L305).

**Comment by LaVLaS** [comment]
We'll be updating the community operator version to a recent stable weekly release, `1.0.4` or `1.0.5`, soon. The operator [kustomize/overlay](https://github.com/opendatahub-io/opendatahub-operator/tree/master/kustomize/overlays/opendatahub) directory you linked provides the files you can use to deploy the operator

```bash
# From the odh-operator repo root, you can run kustomize to manual build the deployment files
cd kustomize/overlays/opendatahub
# Change the Deployment image to official odh operator latest release
kustomize edit set  image aipipeline/kubeflow-operator=quay.io/opendatahub/opendatahub-operator:v1.0.4
# Dump all-on-one yaml to stdout. You can pipe it to oc apply for a manual deployment
kustomize build
```
You should be able to manage your own `kustomization.yaml` file that points to that `opendatahub` overlay with an additional section to overwrite the image.
```yaml
images:
- name: aipipeline/kubeflow-operator
  newName: quay.io/opendatahub/opendatahub-operator
  newTag: v1.0.4
```

**Comment by goern** [comment]
Is this an architectural discussion that should take place upstream?
