### ISSUE TITLE
Remove the requirement to be in operate-first org for cluster authentication

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2061]
This introduces an extra step to onboarding that I'm not sure we need. This wasn't the case before, but was introduced when switching to identitatem: 

https://github.com/operate-first/apps/blob/master/acm/overlays/moc/infra/identitatem/authrealms/primary.yaml#L12

**Comment by durandom** [comment]
@HumairAK I think requiring this extra step for the infra cluster is ok, just to make sure we don't accidentally expose something.
Smaug doesn't have this requirement.

I'll close this, re-open if you think it should be treated different

/asssign @HumairAK 
/close
