### ISSUE TITLE
Permissions issues when impersonating users in groups

### ISSUE THREAD

**Issue by dystewart** [operate-first/apps#2076]
In the smaug cluster, when impersonating a user is a group, say the Curator group, the group's permissions are not extended to the impersonator. 

That is users in the curator group have curator admin access in curator namespaces but the same is not true for an admin impersonating a user in the group

**Comment by dystewart** [comment]
@HumairAK I'd like to try adding just myself to the sudoers group in smaug since the impersonation using the sudoers role in the morty cluster does not seem to have these issues.

In other words I want to try impersonating the user after granting myself admin access via system:admin through sudoer role and see if the behavior is different

**Comment by durandom** [comment]
@dystewart can you provide an example on how to reproduce this issue? E.g. a set of commands or clicks in the UI?

/assign @dystewart
