### ISSUE TITLE
Add the opentelemetry collector operator (RH distributed tracing data collection operator) to Smaug

### ISSUE THREAD

**Issue by sallyom** [operate-first/apps#2099]
@HumairAK this is an operator that should be available on Operator Hub
https://docs.openshift.com/container-platform/4.9/distr_tracing/distr_tracing_install/distr-tracing-installing.html?extIdCarryOver=true&sc_cid=701f2000001Css5AAC#distr-tracing-install-otel-operator_install-distributed-tracing
Hopefully, this will be easy to install in Smaug! 
Once installed, users can deploy in their own namespace a `Jaeger` CR + an `OpenTelemetryCollector` CR - with these, it offers a complete way to collect and visualize trace data from an instrumented application. 

I will add docs similar to the distributed tracing platform docs and a blog explaining how to use these, and with an example application.

**Comment by durandom** [comment]
@sallyom IIRC you have installed an operator for jaeger / opentelemetry?
If so, could you link a PR here and let us know if this can be used by other users of the platform?
