### ISSUE TITLE
Migrate Post-install CNV steps to cluster-scope application

### ISSUE THREAD

**Issue by tumido** [operate-first/apps#211]
Finalize migration of post-install CNV setup to ArgoCD.
https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/playbook-postinstall.yml

Migrate content from:
- [ ] https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/authz/tasks/main.yml
- [ ] https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/tls/tasks/main.yml
- [ ] https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/moc-sso/tasks/main.yml
- [ ] https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/registry/tasks/main.yml

Investigate if the following needs migration as well:
- [ ] https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/bmh/tasks/main.yml
- [ ] https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/firewall/tasks/main.yml
- [ ] https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/hostpath/tasks/main.yml
- [ ] https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/public-net/tasks/main.yml

/sig devops

**Comment by HumairAK** [comment]
Since the new cluster is no longer using the moc-cnv-sandbox repo, I think this is stale, closing. Please re-open if there's more to be done.
