### ISSUE TITLE
Collect all kubeadmin credentials for all clusters to bit warden

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2116]
As discussed in our last sig ops meeting, we would like to have all cluster kube admin creds on bit warden where all relevant parties have access to it, as a failsafe for authentication.

**Comment by durandom** [comment]
@HumairAK we have all credential collected except for os-climate. Are those stored in another vault?

/assign @HumairAK

**Comment by HumairAK** [comment]
@redmikhail can you update these values in the operate-first vault? 

It is the `KubeAdmin Credentials (All Clusters)` bitwarden vault secret under the `operate-first` collection, you should have access to it.
