### ISSUE TITLE
[Metrics] Opf-Kafka metrics aren't available 

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#215]
We have Pod Monitors from [upstream ODH](https://github.com/opendatahub-io/odh-manifests/blob/master/prometheus/operator/base/kafka-podmonitors.yaml), but we still need to override them to add a namespace selector ([docs](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#podmonitorspec)) since the opf-kafka deployment is in a different namespace than the opf prometheus.

**Comment by 4n4nd** [comment]
cc @pacospace @harshad16

**Comment by anishasthana** [comment]
I can pick this up since I wrote the original monitors. Is it something we need done asap?

**Comment by pacospace** [comment]
> cc @pacospace @harshad16

Thanks @4n4nd! We are interested :)

**Comment by harshad16** [comment]
> I can pick this up since I wrote the original monitors. Is it something we need done asap?

we are interested, it would good have them.

**Comment by 4n4nd** [comment]
metrics aren't available yet :(
@anishasthana will look into this

**Comment by anishasthana** [comment]
https://github.com/operate-first/apps/pull/384 _actually_ fixes this :-)
