### ISSUE TITLE
Use of loki operator in the logs stored

### ISSUE THREAD

**Issue by harshad16** [operate-first/apps#2151]
We are currently deploying Loki based on deployment manifests and maintaining them.
There seems to be an official [loki operator](https://github.com/grafana/loki/tree/main/operator) available, maybe it would be great to check if it could make our life easier.

**Comment by durandom** [comment]
I will close this in favor of the upcoming multi cluster observability stack

https://github.com/operate-first/apps/issues/2472

/close
