### ISSUE TITLE
Vault backup job failing

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2210]
see failed jobs here: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/vault/pods?orderBy=desc&sortBy=Created 

it's failing at [step 2](https://github.com/operate-first/apps/blob/master/vault/overlays/moc/smaug/backup-job/task.yaml#L67)

My guess the s3 connectivity is not work, we should confirm first that the morty bucket as described [here](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/vault/secrets/backup-job) works. 

Try using the test pod [here](https://github.com/operate-first/apps/blob/master/vault/overlays/moc/smaug/backup-job/toolkitpod.yaml) to help diagnose the issue.

**Comment by durandom** [comment]
@HumairAK I see the latest backup jobs succeed. Can we close this?

/assign @HumairAK
