### ISSUE TITLE
add precommit documentation to contributing guidelines

### ISSUE THREAD

**Issue by durandom** [operate-first/apps#2213]
add a section similar to https://github.com/thoth-station/core/blob/master/CONTRIBUTING.md#requirements-for-pull-requests-pr to our contributing.md

**Comment by HumairAK** [comment]
We have some [here](https://github.com/operate-first/apps/blob/master/contributing.md#tests) anything in particular that's missing in your opionion?

**Comment by durandom** [comment]
fixed via https://github.com/operate-first/apps/pull/2346
