### ISSUE TITLE
Operatorhub.io catalog source provides broken banzaicloud vault operator

### ISSUE THREAD

**Issue by dystewart** [operate-first/apps#2236]
The 'catalogSource' installed in Smaug in #1640. 
The image being pointed to in the catalogsource being used by the NERC folks (who have a working vault operator) is different than the one we are pointing to: see [our operatorhub.io catalogsource image](https://github.com/operate-first/apps/blob/5b3c2ce6d4ff2613dccb2156a65f6b028f46d737/cluster-scope/base/operators.coreos.com/catalogsources/operatorhubio-catalog/catalogsource.yaml#L8) vs. [nerc operatorhub.io catalogsource image](https://github.com/nerc-project/nerc-k8s-operators/blob/551c49d9ace0356194a6dd285422a1d5174f3079/k8s/base/vault/catalogsources/operatorhubio.yaml#L8)

You can see the error we're getting in Smaug here: [https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/banzaicloud-vault/operators.coreos.com~v1alpha1~Subscription/banzaicloud-vault](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/banzaicloud-vault/operators.coreos.com~v1alpha1~Subscription/banzaicloud-vault)

I've also had success with the catalogSource used by the NERC team so I think the solution here is to either create a new catalogsource or we could simply update the image.
Any suggestions/preferences?

**Comment by durandom** [comment]
@dystewart I'm not seeing any errors in smaug following the link. 
I also think our vault instance is operational.

Do you mean this "Unknown failure" in the screenshot?

<img width="938" alt="image" src="https://user-images.githubusercontent.com/161888/192524117-b3f03fa4-5d14-4539-abb2-0b5b193d4b22.png">

@HumairAK do we have any issues with vault? 

/assign @HumairAK
