### ISSUE TITLE
JupyterHub size selection remembered, then forgotten

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [operate-first/apps#2250]
A notebook I started yesterday was reaped this morning.  I went to restart it, and the Container Size parameter (1 CPU / 8GB RAM) seemed to be remembered.  Yay!  I then started the notebook, only to find that the promised selection was not, in fact, communicated back to the initialization routine.  It started instead a notebook with 2GB RAM default, which is too small to even resume the notebook(s) I had open (see red lettering at bottom of screenshot):

![Screen Shot 2022-08-12 at 6 38 30 AM](https://user-images.githubusercontent.com/72577720/184338491-90cf466c-548a-469f-833a-297d66751dc7.png)

**Comment by durandom** [comment]
@erikerlandson @MichaelClifford is this an issue we could raise with the ODH team? Would you be able to reach out to them?

/assign @durandom

**Comment by erikerlandson** [comment]
@durandom   the problem is in the ODH launcher menu, so arguably it is an ODH issue.  It's kind of bad - people are unable to choose their cpu and ram settings, and so can't run their notebooks properly.

**Comment by erikerlandson** [comment]
xref: https://github.com/operate-first/apps/issues/1918

**Comment by MichaelTiemannOSC** [comment]
Re-upping the fact that just now I restarted a notebook after what appears to have been a server bounce.  The restart page "remembered" that I had requested an 8GB notebook and told me that's what it was going to request.  I let it proceed, and got the 2GB notebook that this issue is about.

**Comment by MichaelTiemannOSC** [comment]
This morning I spawned a Jupyter notebook for the first time in a while.  I had read that we've changed the sizing default and was happy to be greeted by the offer to start a notebook with 8GB RAM / 1 CPU.  When the notebook finished spawning, it showed that 1.9GB of its 2GB RAM was already used.  Can we please get this fixed?
