### ISSUE TITLE
Switch to manual subscriptions instead of automatic for operators

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#227]
We would like to avoid surprises on this front, as automatic roll outs could introduce unexpected disruptions to the system. As witnessed [here](https://github.com/operate-first/support/issues/83?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE1NjcwNjQxMTE6MTA5MDQ5Njc%3D#issuecomment-776080408)

**Comment by tumido** [comment]
FTR: All our current subscriptions have automatic install plan approvals, therefore all the operators update automatically.

If we want to switch to `Manual`, we need to have alerting on new `InstallPlan`s availability in place. So we are aware the operators are updateable.

**Comment by HumairAK** [comment]
> If we want to switch to Manual, we need to have alerting on new InstallPlans availability in place.  

I suggest we move to manual first, and then have a follow up issue to add monitoring for installplan availability, rather than be blocked on this until we have monitoring in place.
