### ISSUE TITLE
CI checks are run on on yaml manifests that are not part of cluster

### ISSUE THREAD

**Issue by mimotej** [operate-first/apps#2294]
In following [PR](https://github.com/operate-first/apps/pull/2289) there was a change in `.prow.yaml` which should not trigger `kustomize-build` and `kubeval-validation` jobs. These jobs were triggered and it let to failure of these tests. We should try to address that.

**Acceptance criteria**
- [ ] `kustomize-build` and `kubeval-validation` are not triggered when changing files which are not part of the clusters or they end without failling

**Comment by durandom** [comment]
@mimotej if you have a quick fix, can you add it to to config? Maybe a path filter or something?
If not, I would not care too much, since changes to those yaml files rarely happen.

feel free to close it without a resolution :)

/assign @mimotej

**Comment by mimotej** [comment]
@durandom This was somewhat addressed in https://github.com/operate-first/apps/pull/2321 .  I don't think there is a simple change in actual script to fix this and current change in prow seems to work just fine. So we can close this for now...
