### ISSUE TITLE
Onboard jerry

### ISSUE THREAD

**Issue by durandom** [operate-first/apps#2350]
jerry is a new cluster at IONOS
the deployment was done via https://github.com/operate-first/ionos-openshift/tree/main/terraform-ocp

now following https://www.operate-first.cloud/apps/content/notebooks/onboarding_new_cluster.html

the completion of this issue should also result in completion of https://github.com/operate-first/support/issues/740

- [x] https://github.com/operate-first/apps/pull/2271
- [x] https://github.com/operate-first/apps/pull/2272
- [x] https://github.com/operate-first/apps/pull/2349

**Comment by tumido** [comment]
seems resolved to me. closing
