### ISSUE TITLE
OSC cluster-resources app failing to sync servie catalog plugin configmap 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2455]
The configmap added here: https://github.com/operate-first/apps/pull/2381/files 

is failing the sync since the namespace `service-catalog-k8s-plugin` does not exist on these clusters: 

```
namespaces "service-catalog-k8s-plugin" not found
```

Solution: 
Add namespace to osc-cl1 and osc-cl2

**Comment by SamoKopecky** [comment]
The config map is correctly added, issue can be closed.
/close
