### ISSUE TITLE
Enable tekton/openshift pipelines prow integration

### ISSUE THREAD

**Issue by VannTen** [operate-first/apps#2462]
Prow apparently has the capacity to use tetkon pipelines as ProwJob (
see
https://pkg.go.dev/k8s.io/test-infra/prow/config#JobBase (PipelinRunSpec)
https://github.com/kubernetes/test-infra/issues/13874
)

What can we do to enable that support ?

This would allow Apps developper to have composable CI pipelines, with reusable
Task notably.

(Prompted by operate-first/apps#2320, https://github.com/operate-first/apps/pull/2320#issuecomment-1232887003 in particular)

/kind feature

possible alternatives:
- https://pipelinesascode.com/
- ...

**Comment by Gregory-Pereira** [comment]
Closing as op1st is being decomissioned.
