### ISSUE TITLE
Onboard ACM MCO to Operate-First `Infra` cluster

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/apps#2464]
Action items:
- [x] create namespace `open-cluster-management-observability`
- [x] enable external secrets in said namespace
- [x] Generate pull-secret. Create an external secret in git for it and reference it.
- [x] create secret for object storage.  Create an external secret in git for it and reference it.
- [x] verify the observability api-version exists
    - done: 
    ``` 
    $ oc api-versions | grep "observability.open-cluster-management.io/v1beta1"
    observability.open-cluster-management.io/v1beta1
    ```  
- [x] create multiClusterObservability Manifest
- [ ] Discussion should take place about our desired [Thanos Downsampling resolution and retention](https://thanos.io/v0.8/components/compact/#downsampling-resolution-and-retention. Additionally, [the docs](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html-single/observability/index) suggest  that "Depending on the number of managed clusters, you might want to update the amount of storage for stateful sets". See more information from the docs regarding [the Obserability API](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html-single/apis#observability-api).

**Comment by durandom** [comment]
/assign @Gregory-Pereira 

@Gregory-Pereira can you try to sum up the current state and list what is already lined up?
Also try to link the issues that @tumido created for deploying storage on infra.

Is there anything else we can do already to get us prepared once storage is available on infra?
