### ISSUE TITLE
[BUG or Flake] Cannot Access Vault

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/apps#2469]
# Issue summary

I was following the steps documented [here](https://www.operate-first.cloud/apps/content/vault_eso/add_external_secrets_to_ns.html), specifically checking if the correct role to access 
 had been given to enable the namespace (opf-observatorium) to fetch secrets from vault. That being said, when attempting to authenticate through the vault UI I tried multiple methods of authenitcation and none worked. Options tried: [`Github token`, `Token` (openshift), `Username`, `OIDC` and `Github`]. An additional bug to be noted is when attempting to sign in with `OIDC` It will not Enable SSO if a role is entered. However if no role is entered, it brings up the SSO page, and SSO continues to operate succesfully. I can authenticate there, and it shows the following message.
![Screen Shot 2022-08-27 at 11 43 41 AM](https://user-images.githubusercontent.com/19876404/187043998-8583b047-652a-47d0-bc93-8d8a9ec78a16.png)

However, then it says that the window closed too fast and doesn't permit me to login. ![Screen Shot 2022-08-27 at 11 48 17 AM](https://user-images.githubusercontent.com/19876404/187044134-e39ebaa0-7ccd-47c9-a0c2-21f0ea2508ed.png)
I retried all these steps with an incognito browser as well, but that didn't change anything. After 10 minutes of retrying authentication with `OIDC` it finally worked, not sure why. This should be investigated to ascertain wether this was a bug or a flake. While this did work eventually, I was able to reproduce it immediately by singing out of vault and signing back in.
/cc @Gregory-Pereira (I will self-assign when I have time to debug the issue)
/cc @HumairAK

**Comment by durandom** [comment]
@Gregory-Pereira is this working now? Did you get to the bottom of it?

/assign @Gregory-Pereira

**Comment by tumido** [comment]
This issue seems stale, closing.
