### ISSUE TITLE
How to access Elasticsearch API endpoint

### ISSUE THREAD

**Issue by drbwa** [operate-first/apps#247]
Apologies for the (potentially) newbie question. How can I find the ES API endpoint for our cluster logging deployment? I only have access to the open-aiops project.

**Comment by tumido** [comment]
Good question. I don't think we have that documented yet.

/sig documentation

Would this route help?
https://elasticsearch-openshift-logging.apps.cnv.massopen.cloud/

**Comment by HumairAK** [comment]
Thanks for the issue @drbwa,  this essentially the same issue as [this](https://github.com/operate-first/apps/issues/229) so let's discuss there. The route linked by @tumido will work if we use a bearer token with certain levels of access, but we haven't really applied any roles/permissions for general usage, this is next on our list.

Closing this, let's continue in the thread linked above :)
