### ISSUE TITLE
Kepler Edge Demo Environment Set up

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2490]
@husky-parul is working on a demo: _**Use GitOps to schedule workloads following anti-sun pattern in a Federated Learning at Edge**_

We have identified OS-Climate cluster cl1 as the ideal place to house this demo. The project has a few requirements that need to be met before @husky-parul can start building out the demos that connect the different cloud services together, these items are: 

- [x] OS-Climate namespace on boarding
  - [x] Get husky-parul & sallyom onboarded on the namespace
~- [ ] Is it possible to get geographically spread node on os-climate, e.g(in different timezones)~
- [x] Separate repo to create PRs against for the demo (we do not want automated merges to apps repo)
- [x] node requirements for osc-cl1
  - [x] 3 nodes on OSCL1
    - [x] 3 different cpu frequencies (possible candidates: m4/m5/m6)
    - [x] Workloads should be able to set tolerances to node taints.
    - [x] 3 isolated nodes3 (with taints to only allow workloads created by @husky-parul )
    - [x] Different generations of m series.
- [ ] Deploy CO2-Signal
- [x] Deploy separate Kafka cluster within @husky-parul 's namespace in osc-cl1 
- [x] Create ArgoCD app for managed demo app in user namespace
- [ ] Separate UWM instance that scrapes kepler + api backend metrics
- [ ] Grafana in user namespace

Current timeline requires this to be in place by Oct 10th

**Comment by HumairAK** [comment]
Fyi @sallyom  + @cooktheryan

**Comment by redmikhail** [comment]
Nodes have been added , all of them have following labels :
```
          node-role.kubernetes.io/kepler-edge: ''
          node-role.kubernetes.io/worker: ''
          node-role.kubernetes.io/osc-platform: ''
```
Application will need to define affinity to  `          node-role.kubernetes.io/kepler-edge: ''` 
All three nodes also have taint 
```
      - key: node-role.kubernetes.io/kepler-edge
        effect: NoSchedule
```
Application should have toleration to existence of this taint
Additionally we may need to adjust kepler daemonset to have toleration to the same taint and preferably affinity to `          node-role.kubernetes.io/osc-platform: ''`

**Comment by HumairAK** [comment]
Argocd app here: https://argocd.operate-first.cloud/applications/kepler-edge-demo-osc?resource=sync%3AOutOfSync 
Gh repo housing demo artifacts: https://github.com/operate-first/kepler-edge-demo

**Comment by HumairAK** [comment]
will set up grafana datasource on already existing grafana instance instead of deploying another one (less to manage this way)
