### ISSUE TITLE
Upgrade to ODH 1.3 For Smaug, osc-cl1, osc-cl2

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2506]
This will require updating the branches in https://github.com/operate-first/odh-manifests
Then ensure the kfdefs here point to the appropriate branches: https://github.com/operate-first/apps/tree/master/kfdefs

Update any configurations in the `kfdefs` folder as needed.

Update them in the following order: 
- [ ] osc-cl1
- [ ] osc-cl2
- [ ] smaug

**Comment by Gregory-Pereira** [comment]
taking a look
