### ISSUE TITLE
increase stockage space and create PVs

### ISSUE THREAD

**Issue by sostrades-radouanbouadel** [operate-first/apps#2523]
hello, 
I need to increase stockage space and create PVs for SOSTRADES project, i have to create many applications. it's possible to ask for 100Gi ?

it's normal that i can't see the PVs: 
`$ oc get pv`
`Error from server (Forbidden): persistentvolumes is forbidden: User "sostrades-radouanbouadel" cannot list resource "persistentvolumes" in API group "" at the cluster scope` 

thinks in advance

Radouan

**Comment by HumairAK** [comment]
What cluster is this for? osc-cl2 I'm assuming? 

@redmikhail

**Comment by sostrades-radouanbouadel** [comment]
yes

**Comment by sostrades-radouanbouadel** [comment]
there is an action to be done on my side?
