### ISSUE TITLE
Deploy Cerebro in openshift-logging

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#254]
As we continue to manage/get used to the Elasticsearch provisioned by CLO, we should consider deploying [cerebro](https://github.com/lmenezes/cerebro) so we can get a better visual admin panel for the ES instance in `openshift-logging`.

**Comment by tumido** [comment]
btw, how did we got the elasticsearch route? Was the route deployed manually during the CLO debugging? It seems it's not tracked in git.

cc @HumairAK @4n4nd

**Comment by HumairAK** [comment]
@tumido  the route isn't technically supposed to be official just yet, as the attached issue is still active [here](https://github.com/operate-first/apps/issues/229), the route will need to be added declaratively, I had been holding off until we settle on a way for users to authenticate themselves.

**Comment by HumairAK** [comment]
don't think this is a priority atm, closing, and can re-open if we need it later.
