### ISSUE TITLE
Prepare overlays for backup MOC cluster

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#262]
There are some very moc specific configurations within the moc overlay, we would like to abstract these out so that if/when we move to a backup cluster there is little downtime. 

We should consider documenting all the essential bits, as we would like the process of enabling a new cluster to be fast.

**Comment by tumido** [comment]
So.. all but one of the currently tracked applications from the `apps` repo would work just fine.

The `local-storage` is the exception: it requires direct access to storage devices. This depends on the backup cluster configuration - if there is a directly available storage or not. Based on that, the `local-storage` application has to be changed.

**Comment by HumairAK** [comment]
With the cluster migration complete, this issue is resolved + stale. Closing.
