### ISSUE TITLE
deploy Prow RBAC

### ISSUE THREAD

**Issue by goern** [operate-first/apps#263]
deploy https://github.com/thoth-station/thoth-application/tree/master/prow/overlays/cnv-prod-test-pods

/kind feature
/sig devops

**Comment by tumido** [comment]
As I'm looking at the resources listed in there, those are `Role`s and `Rolebinding`s only. That is a namespaced resource you can deploy from within your own application. There's no need for them to live inside this repo. Either create a new app for those or just reference it in your current `kustomization.yaml` for that namespace.

**Comment by tumido** [comment]
Resolved long time ago
