### ISSUE TITLE
Does current cluster-logging setup get EventRouter logs?

### ISSUE THREAD

**Issue by drbwa** [operate-first/apps#266]
For the purposes of trying to find operational issues in the platform itself, it would be great to have access to platform log events. 

I could not find EventRouter logs in Kibana, which should be under an index called `operate-<something>` (I think). On closer inspection (`oc get pods --selector component=eventrouter -o name -n openshift-logging`), I cannot find any pods for EventRouter. 

Do we want to consider deploying EventRouter to get the types of logs it makes available?

**Comment by tumido** [comment]
Sure, we can deploy it if it helps you.

Can the EventRouter be deployed via CLO operator? Can you please help us and open a PR against here:

https://github.com/operate-first/apps/blob/master/cluster-logging/base/clusterlogging.yaml

**Comment by drbwa** [comment]
After our previous discussion, we have decided to work on the existing set of logs (excluding EventRouter logs). We will revisit this decision after having gained some experience with the current set of logs.

**Comment by HumairAK** [comment]
bump

**Comment by 4n4nd** [comment]
Found something in the openshift docs: https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-eventrouter.html
