### ISSUE TITLE
[Resource Request]: MySQL Deployment Test

### ISSUE THREAD

**Issue by RobotSail** [operate-first/apps#2745]
### Resource Prompt

Create a MySQL Deployment with 5 replicas and 600Gi of storage

**Comment by tumido** [comment]
Can you please use this template so we get most of the boiler plate autocreated?

https://github.com/operate-first/support/issues/new?assignees=first-operator&labels=kind%2Fonboarding%2Cscript%3Ascripts%2Fonboarding.sh%2Ctask-type%3Abash%2Crepo%3Aapps&template=4_onboarding_to_cluster.yaml&title=NEW+PROJECT%3A+%3Cname%3E

We can give you a namespace with custom quota. That storage request should be acceptable.
