### ISSUE TITLE
CNV cluster pods cannot access routes from the infra cluster

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#285]
I tried curling a route from the MOC infra cluster for metrics using one of the pods from the CNV cluster.

```
sh-4.4$ curl http://argocd-dex-server-metrics-argocd.apps.moc-infra.massopen.cloud:80/metrics -I
HTTP/1.0 503 Service Unavailable
Pragma: no-cache
Cache-Control: private, max-age=0, no-cache, no-store
Connection: close
Content-Type: text/html
```

I get a 503 response. I think this is because of a mis-configuration in the CNV cluster that routes all `xxxx.massopen.cloud` addresses to local pods.

**Comment by 4n4nd** [comment]
cc @larsks

**Comment by larsks** [comment]
@4n4nd can you point to the possible misconfiguration? From a pod on the cnv cluster, `http://argocd-dex-server-metrics-argocd.apps.moc-infra.massopen.cloud:80/metrics` resolves to the correct address (`192.12.185.143`, which is the loadbalancer for the moc-infra cluster).

**Comment by larsks** [comment]
From a different openshift cluster (ocp.massopen.cloud, which Naved is working on), I get get a third behavior: the OpenShift "Application is not available" message.

**Comment by 4n4nd** [comment]
@larsks any pod in [this namespace](https://console-openshift-console.apps.cnv.massopen.cloud/k8s/ns/opf-stage-hema/pods) gets a 503 error in response (or "Application is not available" in the body)

**Comment by larsks** [comment]
@4n4nd right, I was able to reproduce that. I was pointing out in my [second comment](https://github.com/operate-first/apps/issues/285#issuecomment-786127398) that there is yet a third behavior visible. This may all become moot if we reinstall the cluster as planned on Monday (discussion in https://github.com/operate-first/SRE/issues/62).

**Comment by 4n4nd** [comment]
> This may all become moot if we reinstall the cluster as planned on Monday

Yeah, I guess we can just wait for the reinstallation and see if that fixes this issue :+1:

**Comment by 4n4nd** [comment]
@larsks unfortunately it looks like this issue was not fixed :(

**Comment by HumairAK** [comment]
Looks like this was resolved, closing.

**Comment by larsks** [comment]
But see https://github.com/operate-first/SRE/issues/125 for details about the problem and the resolution.
