### ISSUE TITLE
Kibana Down?

### ISSUE THREAD

**Issue by drbwa** [operate-first/apps#296]
Apologies in case this is not the right repo for this issue. 

The Kibana dashboard reports that Kibana is in yellow status and does not provide access to its functionality. One particular plugin that stands out as being yellow (the other plugins are all green) is `plugin:opendistro_security@6.8.1` with its status being reported as `Setting up index template.`

**Comment by HumairAK** [comment]
Hello @drbwa thanks for reporting this, I'll be taking a look at this, let's move this to the SRE thread I just created where we post about downtimes/outages [here](https://github.com/operate-first/SRE/issues/98). Thanks!
