### ISSUE TITLE
feat: add openshift-ml-workflows-workshop

### ISSUE THREAD

**Issue by isabelizimm** [operate-first/apps#301]
bring in docs and notebook deployments for https://github.com/isabelizimm/openshift-ml-workflows-workshop

**Comment by tumido** [comment]
Hi @isabelizimm how can we help you with this issue in this repo?

**Comment by isabelizimm** [comment]
Realizing this issue is misplaced + not verbose enough, trying again in correct location (apologies-still learning!)

**Comment by tumido** [comment]
no worries! :slightly_smiling_face: We're happy to help any time, so feel free to (re)open issues in here as well, I didn't mean to discourage you!
