### ISSUE TITLE
Model for versioned subsriptions

### ISSUE THREAD

**Issue by larsks** [operate-first/apps#323]
We're about to find ourselves running multiple versions of OpenShift in different clusters. We're going to need a model for versioned subscriptions; currently everything in `cluster-scope/base/subscriptions` assumes that all clusters are running the same version of operators. This probably won't be true if we have some clusters on 4.6, others on 4.7, etc.

**Comment by tumido** [comment]
I think that's what the overlays are for.

See: https://github.com/operate-first/apps/pull/288
