### ISSUE TITLE
Mechanism for declaratively managing operator upgrades

### ISSUE THREAD

**Issue by larsks** [operate-first/apps#394]
We've set all of our subscriptions to require manually approval for updates. This is great, because the installed operator versions don't change unexpectedly, and we get notification of available updates.

The problem is that it's not clear how best to handle the upgrade.

We could import the pending `InstallPlan` resource into the repository (and set `spec.approved`), but it's not clear that's the correct way of doing this.

**Comment by larsks** [comment]
Wolfgang Kulhanek suggested taking a look at the documentation on Catalog Snapshots (https://github.com/redhat-cop/agnosticd/blob/development/docs/Operator_Catalog_Snapshots.adoc). This doesn't directly solve the problem but suggests a different way of approaching the situation.

**Comment by tumido** [comment]
There's this RFE for Operator Lifecycle management: https://issues.redhat.com/browse/OLM-1804 (targeting OCP 4.9)

And there's this workaround job from OpenShift Gitops for accepting approvals as a OpenShift job:
https://github.com/redhat-canada-gitops/catalog/blob/master/installplan-approver/base/installplan-approver-job.yaml

**Comment by larsks** [comment]
> And there's this workaround job from OpenShift Gitops for accepting approvals as a OpenShift job...

I'm not sure I understand the point of that job. Isn't that doing the same thing as `installPlanApproval: automatic`, but in a much more complicated fashion?

I guess we could adopt a modified version of that and create a one-time job that would approve a *specific* subscription.

**Comment by larsks** [comment]
@tumido so how about this...

- We create an `installplan-approval` cluster role that permits list/get on subscriptions and list/get/patch on installplans.
- For namespaces hosting subscriptions, we create an `install-approver` service account, bound to the cluster role.
- To approve an update, we submit a Job that takes as input a subscription name and a desired version (like `kubevirt-hyperconverged-operator.v2.6.0`, and then:
  - Looks up the named subscription
  - From that subscription, get the  InstallPlanRef
  - Look up the specified InstallPlan
  - Verify that it matches the requested version
  - Patch the install plan to approve the install

The Job only completes successfully if it find a matching installplan
and either (a) it is already approved or (b) it can be patched
successfully.

Otherwise the job retries until successful.

This way we get an explicit record in our commit history recording and implementing the decision to upgrade to a specific version.

**Comment by larsks** [comment]
Although for that sort of thing a persistent service would probably be a better solution. Deploy it once, then feed it configuration via a ConfigMap.

**Comment by tumido** [comment]
@larsks the solution you propose basically means to create an operator of sort. :smile: 

We can use Tekton or Argo and have a pipeline/workflow template in place and just submit it with some parameters.

The problem is that such job is never declarative - if we track these jobs in our repos and we then redeploy the cluster we would end up running all the previously declared install plan approval jobs on the new cluster. And since the context on this new cluster would be different, the result would differ as well. And that's not declarative.

I don't have any good plan in my sleeve for this though. IDK.

**Comment by larsks** [comment]
>  the solution you propose basically means to create an operator of sort.

Well, let's try that.

We create a persistent Pod for handling update approvals. We feed it a
configuration like this that gets mounted inside the pod:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: updateconfig
  namespace: default
data:
  kubevirt-hyperconverged.yaml: |
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
    version: kubevirt-hyperconverged-operator.v2.6.0
  local-storage-operator.yaml: |
    name: local-storage-operator
    namespace: local-storage
    version: local-storage-operator.4.7.0-202103060100.p0
```

The pod loops over the configmap keys, for each one it will :

- Look up the named subscription
- Find the active installplan
- Check that the installplan matches the requested version
- If the installplan matches the requested version and it has not
  yet been approved, approve it

Prototype code is [here](https://github.com/larsks/update-approver).

Deployment manifests are [here](https://github.com/larsks/update-approver-deploy).

This *is* a declarative solution, in the sense that we are declaring
which updates are explicitly approved. If we reinstall a cluster and
we end up with more recent operators...it doesn't matter; this code
will see that the version doesn't match and won't do anything. When
there's an update that needs approval, we update the ConfigMap and
push the changes. There are no stale approval jobs or anything like
that that would cause problems.

**Comment by tumido** [comment]
Yup, that looks like a clever solution to me. Also if only the latest operator versions are stored in the configmap, it is declarative. I've had a bit of a different vision that didn't comply with that. This solution is very good. The only misfortune here is that it's a custom solution and lets hope OpenShift or OpenShift GitOps can solve it in some generic, upstream way in the future. :smile:

**Comment by larsks** [comment]
How should I handle proposing this for adopting in our environment? The deploy manifests will obviously be handled as a pull request against our configuration repositories, but the code itself should be reviewed as well.

**Comment by tumido** [comment]
Honestly I don't know.. we don't have much experience for nursing inhouse projects yet... Maybe we can create an empty repository in OperateFirst and you can then do a pull request with the codebase? We would also like to build it using s2i and AiCoE CI if we want to do things properly.

@HumairAK @durandom wdyt?

**Comment by larsks** [comment]
I've created https://github.com/operate-first/update-approver/pull/1 with the code for review.

**Comment by tumido** [comment]
Seems like automatic install plans is the way to go for now... so far no troubles were caused by this. I think we can close this issue now.
