### ISSUE TITLE
Add Elasticsearch route to a public facing location.

### ISSUE THREAD

**Issue by drbwa** [operate-first/apps#395]
The old route we had for Elasticsearch does not seem to be valid anymore after the reincarnation of MOC and we could neither find nor figure out the new route :-(

**Comment by tumido** [comment]
@drbwa the route is there. With the cluster reprovisioning it was also renamed (`s/cnv/zero` in the host name). This route should work:

https://elasticsearch-openshift-logging.apps.zero.massopen.cloud/

**Comment by HumairAK** [comment]
@drbwa apologies, yes the route updated as @tumido has pointed out. I'm going to rename this issue to store this route on the support readme, and turn it into an action item.

**Comment by drbwa** [comment]
@HumairAK should we expect this route to ES to work for members of our project (open-aiops) at the moment?

**Comment by HumairAK** [comment]
@drbwa bah it slipped my mind that the route certs needed to be update after the cluster reboot, #434 should fix this issue.

**Comment by HumairAK** [comment]
@drbwa it should work now, let us know if it does/doesn't!
