### ISSUE TITLE
Implement Resource Quotas for the different namespaces 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#438]
I think it's time we start thinking about a strategy for implementing resource quotas for our namespaces, currently anyoen can request as much as they want and this is kinda of a disaster waiting to happen imo. 

I was thinking of having a standard tier like how PSI has done: bronze/silver/gold, with increasing resources permissions, we can also allow for custom resourcequotas for more niche situations. 

We will also need a [LimitRange](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#create-a-limitrange-and-a-pod) that's reasonable, so that current pod creations that do not specify limits are not affected.

**Comment by tumido** [comment]
Yup. Sounds good to me. I've found the culprit blocking our systems right now but in general yes, definitely - we need quota and rather asap.

/priority critical-urgent

**Comment by tumido** [comment]
Related: This is the offender: https://github.com/operate-first/support/issues/159

**Comment by tumido** [comment]
We need an ADR and some communication before we start enforcing this. Friday is a bad day for such changes also :slightly_smiling_face:

**Comment by HumairAK** [comment]
@tumido I think we can add the resource quota tiers + limit ranges but not enforce it until next week. We can reference them in the ADRs as well.

**Comment by HumairAK** [comment]
Adr issue: https://github.com/operate-first/blueprint/issues/64

**Comment by tumido** [comment]
> @tumido I think we can add the resource quota tiers + limit ranges but not enforce it until next week. We can reference them in the ADRs as well.

> Edit: nvm looks like we already did merge it in.

precisely, that can is what I though about

**Comment by HumairAK** [comment]
Implemented in #439
