### ISSUE TITLE
Cluster upgrade - 4.7.0 - 4.7.2 - MOC Zero

### ISSUE THREAD

**Issue by tumido** [operate-first/apps#455]
Upgrade path tracking for https://github.com/operate-first/apps/pull/421

**Comment by tumido** [comment]
PR was merged, upgrade started

30/31 Cluster operators upgraded successfully - `network` fluctiating

**Comment by tumido** [comment]
@larsks noticed troubles on `ctrl-0` master node - node is stuck, tried kicking it.

Currently rebooting that node continues to be problematic. Getting stuck in the BIOS.

**Comment by HumairAK** [comment]
from @larsks  in slack: 

There has been a power failure at the data center facility hosting the operate first clusters. The hosting facility sent out the following alerts:

```
The utility power feed to the MGPCC facility was interrupted at approximately 11:55 this morning.
UPS-backed systems are currently running on generator poer.
We will provide an update as soon as we have worked out a plan with HG&E to restore power.
```

**Comment by HumairAK** [comment]
Latest update from @lars on slack: 

```
 Power has been restored on the MGHPCC utility power feed.  We are checking with HG&E now to make sure the power feed is stable before restarting data center operation.
 ```

**Comment by HumairAK** [comment]
The MOC SSO service is back up now.

**Comment by tumido** [comment]
Power was restored, incident explanation from MOC:

```
By the end of the day on Monday, HG&E had identified and addressed the root cause of the problem that led to the outage that occurred at 11:45AM on that day.  Here’s a high level summary:
There are two substations that supply energy to the City of Holyoke from the New England Power grid and local generators such as the dam.  Either one can power the entire city.  For the first time in more than 30 years.  There were two related incidents that affected both substations.  This resulted in a city-wide power outage lasting approximately 35 minutes.:
(1)   Due to high winds, a tree fell and its upper branches made contact with a transmission line, causing a momentary short circuit that disabled one of the two substations.  Ordinarily, this event would have caused a power sag as the second substation picked up the load.
(2)   On the second substation, a protection device incorrectly interpreted the event on the first substation, and triggered a shutdown.  As a result, both substations went off-line instead of just one.
HG&E re-energized both substations after inspecting the relevant equipment and lines.  After determining the root cause, they changed the settings on the protection devices so that they will function properly if this condition occurs again.
```

Then we proceeded to upgrade the cluster node by node.

- We had to manually evacuate the pods for istio and ceph (causing the OCS to be in degraded state)
- We had to shut down the Decorus team's VMI, next time we would like to set up a live migration https://kubevirt.io/2020/Live-migration.html
- Additionally the unscheduleble `os-wrk-1` node was also upgraded though we know it was faulty, @larsks removed it from the cluster afterwards. It will be re-provisioned.

**Comment by tumido** [comment]
Upgrade to 4.7.2 is complete now.
