### ISSUE TITLE
re-organizing odh "app" folder

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#466]
I think in hindsight it may not have been a good idea to mix our odh kustomize manifests with the overrides, because the folder [here][1] has become a bit of a mess. I think we can possibly untangle this by doing the following: 

- Move kfdefs from `apps/odh` to `apps/kfdef` 
- Any resources added via kustomize in `apps/odh` but not through `/odh` should go in a separate app at the root of `apps`
- Leave only overrides in the `odh` folder so it's purpose is clear, and we can better identify changes to ODH that we have made for operate-first vs upstream `odh-manifests` 

WDYT?

[1]:https://github.com/operate-first/apps/tree/master/odh

**Comment by tumido** [comment]
I agree with the apps reorganization for ODH. I also think we can also go a bit further than this:

Initially ODH was our only supported workload. Right now the focus shifted and ODH is one of many. I think it would be only relevant to rename all the `opf-*` namespaces which are ODH specific to use `odh-*` prefix instead and create `odh` user group that can admin those namespaces including upstream ODH and downstream RHODS folks. WDYT? 

Keep in mind that namespaces can't be renamed so we would need to recreate the namespaces and/or remove the workloads if possible. We can also do this in case we will migrate ODH to any other than Zero cluster in the future.

**Comment by HumairAK** [comment]
Agreed
How about we break this into 2 chunks then: 
1) Re-organize structure
2) Move to odh-* namespaces 

2, will probably need to be done in smaller chunks per component, with announcements for services like JH etc.

**Comment by tumido** [comment]
Yup, let's start with the first point.

Once we're done with that we can slowly migrate the namespaces one by one. I'm worried about moving PVCs between namespaces. This needs to be tested first.

**Comment by HumairAK** [comment]
I don't think we're moving to `odh-*` namespaces anytime soon, I actually think there might be some benefit still to having `opf-*` namespaces, to differentiate what _we_ as the admin team manage vs regular users. Anyways I think the current state is fine, going to close -- if someone disagrees please re-open.
