### ISSUE TITLE
Update ArgoCD to 2.0+

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#498]
[ArgoCD 2.0](https://github.com/argoproj/argo-cd/releases) is out, lots of changes were introduced. We should start planning onupgrading it within the coming days/weeks. We will also need to trickle changes downstream.

**Comment by HumairAK** [comment]
Relevant: https://argoproj.github.io/argo-cd/operator-manual/upgrading/1.8-2.0/

**Comment by anishasthana** [comment]
As part of this will we also want to move away from the app-of-apps structure we do? Or is that a change for later down the road.

**Comment by tumido** [comment]
I think we can do it as 2 separate steps. I think the upgrade is a complex thing enough on its own. No need to overcomplicate things. It should be a consecutive PR, sure, but not necessary a merge together kind of thing.

**Comment by HumairAK** [comment]
Done
