### ISSUE TITLE
URLs to Apps on Docs

### ISSUE THREAD

**Issue by oindrillac** [operate-first/apps#504]
Hello Team,

I had a qs about certain URLs to applications on the operate first site. Just want to make sure that they are correct.

* http://loki-distributor-opf-observatorium.apps.zero.massopen.cloud/ on https://www.operate-first.cloud/users/apps/docs/observatorium/loki/README.md - gives me a 404
* https://odh-message-bus-kafka-bootstrap-opf-kafka.apps.zero.massopen.cloud/ on https://www.operate-first.cloud/users/apps/docs/odh/kafka/README.md gives me an error "Your connection is not private"
* http://ml-pipeline-ui-kubeflow.apps.zero.massopen.cloud on https://www.operate-first.cloud/users/apps/docs/kubeflow/kubeflow-pipelines/README.md says application not available

**Comment by HumairAK** [comment]
> http://loki-distributor-opf-observatorium.apps.zero.massopen.cloud/ on https://www.operate-first.cloud/users/apps/docs/observatorium/loki/README.md - gives me a 404 

and 

> https://odh-message-bus-kafka-bootstrap-opf-kafka.apps.zero.massopen.cloud/ on https://www.operate-first.cloud/users/apps/docs/odh/kafka/README.md gives me an error "Your connection is not private" 

are not addressing webpages, so they are not intended to be loaded into the web browser, rather they are consumed directly by other services/cli/tools (for example in the loki docs you linked you can see the curl commands to interact with it). 

>http://ml-pipeline-ui-kubeflow.apps.zero.massopen.cloud on https://www.operate-first.cloud/users/apps/docs/kubeflow/kubeflow-pipelines/README.md says application not available 

This one I"m not sure of, @4n4nd ?
AFAIK the kubeflow pipelines link is: http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/

**Comment by tumido** [comment]
The `ml-pipelines-ui` route was a route we had on CNV, but it wasn't tracked in git - we didn't deploy it to `zero`. Kubeflow is intended to be accessed via the Istio gateway (which is dumb for multi-tenant envs). We might expose some extra additional routes for convenience once we upgrade Kubeflow.

**Comment by oindrillac** [comment]
👍 thanks for clarifying, so should we change the kubeflow pipelines url to http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/_/pipeline/ instead ?

**Comment by HumairAK** [comment]
@oindrillac  yes

**Comment by 4n4nd** [comment]
@oindrillac I think we can change it to http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/pipeline
