### ISSUE TITLE
Have ArgoCD manage JupyterHub database secret

### ISSUE THREAD

**Issue by anishasthana** [operate-first/apps#545]
https://github.com/opendatahub-io/odh-manifests/pull/362 Introduced the ability to use secrets to create the JupyterHub Database user. While everything is open in operate first, I think having the secret be something that is managed by ArgoCD + KSOPS would show how things would work in an actual production setting. https://github.com/red-hat-data-services/odh-manifests/pull/30/files contains patches that show how you could point JupyterHub at the ArgoCD managed secret

**Comment by anishasthana** [comment]
https://github.com/red-hat-data-services/odh-manifests/pull/73 has an example PR as well :-)

**Comment by tumido** [comment]
Awesome suggestion @anishasthana ! Wanna send a PR? :grin:
