### ISSUE TITLE
Docs for dev environment setup of odh apps

### ISSUE THREAD

**Issue by hemajv** [operate-first/apps#571]
We need to include documentation for instructions on deploying odh components in a dev environment

**Comment by HumairAK** [comment]
We should adapt the `dev` folders in the `cluster-scope` and `odh-operator` apps, and come up with an easy path to quickly set up dev environments without much hassle. I think right now it's not entirely clear how they work and/or can be leveraged.

**Comment by tumido** [comment]
Stale, closing. Probably not intended workflow anymore. Advise users to use upstream docs for dev setup.
