### ISSUE TITLE
[BUG]openshift-pipeline is failing due to lack of roles 

### ISSUE THREAD

**Issue by harshad16** [operate-first/apps#581]
while runing tekton based pipeline, the pipeline are failing to execute and on further inspection 
we can view the issues like 
`User "system:serviceaccount:openshift-pipelines:tekton-pipelines-controller" cannot get resource "pods" in API group "" in the namespace "opf-ci-pipelines"`
same for other resource like sa, secrets ,etc.

seems like the role have been over-written.

**Comment by HumairAK** [comment]
@harshad16 can this be closed?

**Comment by harshad16** [comment]
Just test this pipelines
they seem to work,
the solution by @tumido  works.
thanks
