### ISSUE TITLE
Rename repository to be more general

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#63]
Currently we don't have another repo to store non-odh related apps. In the broader scheme of things, from the perspective of operate-first, odh is just another app, and I don't think we really need to have this entire repo be dedicated to odh only. 

I propose we change this repo to be more generic and rename it to ~~operate-first-apps~~ `apps`, and move the odh contents in to a sub directory.

**Comment by HumairAK** [comment]
@durandom  any objections to `operate-first-apps`? I know you prefer to leave out the `operate-first-` prefix, I was hoping to distinguish it from the `argocd-apps` repo however, I don't have a strong objection to naming it just `apps`.

**Comment by tumido** [comment]
Both sounds fine to me. TBH, `github.com/operate-first/apps` looks better than `github.com/operate-first/operate-first-apps`. We can also go a bit more creative with this.. a `herd`/`pack`/`flock` of apps we care of, for example.

**Comment by HumairAK** [comment]
Yeah sure let's go with `apps` then. I don't have any ideas on how to categorize apps (flocks in your analogy) further than this. So `apps` I think is sufficient for now, we can revisit as we onboard more apps and logical groupings may reveal themselves in the future.

**Comment by durandom** [comment]
Hmm, I don't understand why we want to rename, sorry. What's the difference to `argocd-apps` then?
I would still treat this repo as ODH, with some incubation, like observatorium. Or we move the observatorium to the argocd-apps repo.

**Comment by HumairAK** [comment]
@durandom 

argocd-apps hold the ArgoCD Application custom resource only, these resources point to the repositories that argocd will deploy,

For example [this file](https://github.com/operate-first/argocd-apps/blob/main/base/operate-first/kafka.yaml#L11-L12) In the `argocd-apps` repo will deploy kafka [here](https://github.com/operate-first/odh/tree/master/overlays/moc/kafka). 

My understanding is in the future we would like to be open to onboarding more apps besides odh, and afaik observatorium is not odh specific, so instead of having multiple repos like this: 

operate-first/odh
operate-first/non-odh-app-1          (e.g. operate-first/opbservatorium) 
operate-first/non-odh-app-2
...
operate-first/non-odh-app-N

We store them in a single repo with sub directories like so: 
operate-first/apps:
-odh/
-non-odh-app-1
-non-odh-app-2
....
-non-odh-app-N

**Comment by durandom** [comment]
Gotcha, then go for `apps`, since it matches the `argocd-apps` relationship

**Comment by HumairAK** [comment]
Done
