### ISSUE TITLE
Update Docs & Scripts to reflect change from adr 15

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#631]
Changes introduced [here](https://github.com/operate-first/apps/pull/622) need to be reflected in all our docs + scripts. This may require updates to other repositories as well.

**Comment by larsks** [comment]
I was separately working on https://github.com/operate-first/apps/pull/633, which also takes care of the `enable-monitoring.sh` script and adds some tests.

**Comment by HumairAK** [comment]
Hrmm so going through the docs I think these are the only ones left: 

- [ ] https://github.com/operate-first/apps/blob/master/docs/cluster-scope/add_resource_quotas.md 
- [ ] https://github.com/operate-first/apps/tree/master/cluster-scope

But if there are others please list them here. 

For scripts I think this is left: 

- [ ] https://github.com/operate-first/apps/blob/master/scripts/argocd/update_cluster_resources.sh#L41
