### ISSUE TITLE
Increase node reserved memory

### ISSUE THREAD

**Issue by larsks** [operate-first/apps#671]
We frequently see `SystemMemoryExceedsReservation` alerts. We should probably increase the system memory reservation on the workers; it looks like instructions for doing that are [here](https://docs.openshift.com/container-platform/4.7/nodes/nodes/nodes-nodes-managing.html).

(from #669)

**Comment by 4n4nd** [comment]
Related https://github.com/operate-first/apps/pull/673

**Comment by tumido** [comment]
Verify if fixed @tumido

**Comment by tumido** [comment]
@larsks @4n4nd we still have this alert here: https://github.com/operate-first/alerts/issues/3544 It's comming from the MOC Infra cluster.

Can we please repeat https://github.com/operate-first/apps/pull/673 against MOC Infra?
