### ISSUE TITLE
JH Dashboard resource usage by kernel

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/apps#762]
Feature request: As a user of JH and the JH [Dashboard](jupyterhub-user.yaml), I would like to see my resource usage grouped by notebooks. If I have three notebooks (three kernels) running, the dashboard memory and cpu breakdowns could show how much each notebook is using. 
(I'm not sure if we have metrics at this level of granularity but it'd be useful to have this from a user perspective)

**Comment by 4n4nd** [comment]
I am pretty sure we don't have these metrics, but @hemajv might know better

**Comment by hemajv** [comment]
@Shreyanand currently the metrics for monitoring resource usage are kube state "pod" metrics, I don't think we have anything which gives a breakdown by the user's notebook, will have to look into where/how these metrics can be captured
