### ISSUE TITLE
CI failing on kustomize build

### ISSUE THREAD

**Issue by tumido** [operate-first/apps#764]
Probably a remote manifest got changed. Affects all PRs from now:
https://github.com/operate-first/apps/pull/761#issuecomment-863259721

**Comment by HumairAK** [comment]
something funky going on, I tested on `master` with the toolbox 0.3.6 and it ran fine: 

<details> 

<summary> log.txt </summary>

apps (master)$ test-kustomize-build 
checking ./cluster-logging/overlays/moc/zero/configmaps
checking ./cluster-logging/overlays/moc/zero/clusterlogforwarders
checking ./cluster-logging/overlays/moc/zero
checking ./cluster-logging/overlays/dev
skipping ./odh-manifests/prometheus/operator/overlays/openshift-proxy
skipping ./odh-manifests/prometheus/operator/overlays/alerts
skipping ./odh-manifests/kafka/overlays/topics
skipping ./odh-manifests/kafka/overlays/users
skipping ./odh-manifests/dashboard/overlays/cluster-role
skipping ./odh-manifests/dashboard/overlays/custom-image
checking ./kubeflow-components/overlays/moc/zero/profiles
checking ./kubeflow-components/overlays/moc/zero
checking ./kubeflow-components/overlays/moc/zero/rolebindings
checking ./kubeflow-components/overlays/moc/zero/roles
checking ./kubeflow-components/overlays/dev
checking ./argocd/overlays/dev/applications/dev_app
checking ./argocd/overlays/dev/applications
checking ./argocd/overlays/dev/projects
checking ./argocd/overlays/dev
checking ./argocd/overlays/moc-infra/applications
checking ./argocd/overlays/moc-infra/projects
checking ./argocd/overlays/moc-infra
checking ./auth/overlays/moc/zero
checking ./auth/overlays/dev
checking ./vector/overlays/moc/zero
checking ./vector/overlays/moc/zero/opf-observatorium
checking ./vector/overlays/dev
checking ./acme-operator/overlays/moc/zero
checking ./acme-operator/overlays/dev
checking ./moc-nfs-democratic-csi/overlays/moc/zero
checking ./alertreceiver/overlays/moc/zero
checking ./alertreceiver/overlays/moc/common
checking ./alertreceiver/overlays/moc/infra
checking ./kubevirt-hyperconverged/overlays/moc/zero
checking ./kubevirt-hyperconverged/overlays/moc/infra
checking ./kubevirt-hyperconverged/overlays/dev
checking ./acm/overlays/moc/infra
checking ./jupyterhub-idle-culler/overlays/moc/zero
checking ./metallb/overlays/moc/zero
checking ./cluster-scope/overlays/moc/zero
checking ./cluster-scope/overlays/moc/curator
checking ./cluster-scope/overlays/moc/common
checking ./cluster-scope/overlays/moc/infra
checking ./cluster-scope/overlays/dev
checking ./observatorium/overlays/moc/zero/deployments
checking ./observatorium/overlays/moc/zero/grafana-data-sources
checking ./observatorium/overlays/moc/zero/objectbucketclaims
checking ./observatorium/overlays/moc/zero/routes
checking ./observatorium/overlays/moc/zero/serviceaccounts
checking ./observatorium/overlays/moc/zero
checking ./observatorium/overlays/moc/zero/services
checking ./observatorium/overlays/moc/zero/rolebindings
checking ./observatorium/overlays/moc/zero/roles
checking ./observatorium/overlays/dev
checking ./knative/overlays/moc/zero
checking ./kfdefs/overlays/moc/zero/opf-dashboard
checking ./kfdefs/overlays/moc/zero/ds-ml-workflows-ws
checking ./kfdefs/overlays/moc/zero/opf-argo
checking ./kfdefs/overlays/moc/zero/opf-seldon
checking ./kfdefs/overlays/moc/zero/opf-google-spark-operator
checking ./kfdefs/overlays/moc/zero/opf-kafka
checking ./kfdefs/overlays/moc/zero/thoth-infra-prod
checking ./kfdefs/overlays/moc/zero/opf-jupyterhub
checking ./kfdefs/overlays/moc/zero/opf-monitoring/scrape-configs
checking ./kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first
checking ./kfdefs/overlays/moc/zero/opf-monitoring/dashboards/kubeflow
checking ./kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thanos
checking ./kfdefs/overlays/moc/zero/opf-monitoring/dashboards/odh
checking ./kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station
checking ./kfdefs/overlays/moc/zero/opf-monitoring/dashboards
checking ./kfdefs/overlays/moc/zero/opf-monitoring/rules/alerting
checking ./kfdefs/overlays/moc/zero/opf-monitoring/serviceaccounts
checking ./kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors
checking ./kfdefs/overlays/moc/zero/opf-monitoring
checking ./kfdefs/overlays/moc/zero/opf-monitoring/rolebindings
checking ./kfdefs/overlays/moc/zero/opf-monitoring/roles
checking ./kfdefs/overlays/moc/zero/opf-monitoring/secrets
checking ./kfdefs/overlays/moc/zero/opf-monitoring/datasource
checking ./kfdefs/overlays/moc/zero/opf-superset
checking ./kfdefs/overlays/moc/zero/opf-datacatalog
checking ./kfdefs/overlays/moc/zero/opf-jupyterhub-stage
checking ./kfdefs/overlays/moc/zero
checking ./kfdefs/overlays/moc/zero/osc-playground
checking ./kfdefs/overlays/dev/opf-dashboard
checking ./kfdefs/overlays/dev/opf-argo
checking ./kfdefs/overlays/dev/opf-seldon
checking ./kfdefs/overlays/dev/opf-kafka
checking ./kfdefs/overlays/dev/opf-jupyterhub
checking ./kfdefs/overlays/dev/opf-monitoring
checking ./kfdefs/overlays/dev/opf-superset
checking ./kfdefs/overlays/dev/opf-datacatalog
checking ./kfdefs/overlays/dev
checking ./odh-operator/overlays/moc/zero
checking ./odh-operator/overlays/dev
checking ./slack-first/overlays/moc/zero
checking ./local-storage/overlays/moc/zero
checking ./local-storage/overlays/dev
checking ./ceph/overlays/moc/zero
checking ./ceph/overlays/dev


</details>

**Comment by HumairAK** [comment]
For context the error we are encountering in CI: 

```

 checking ./acm/overlays/moc/infra
checking ./acme-operator/overlays/dev
checking ./acme-operator/overlays/moc/zero
checking ./alertreceiver/overlays/moc/common
checking ./alertreceiver/overlays/moc/infra
checking ./alertreceiver/overlays/moc/zero
checking ./argocd/overlays/dev/applications/dev_app
checking ./argocd/overlays/dev/applications
checking ./argocd/overlays/dev
Error: accumulating resources: accumulation err='accumulating resources from '../../base': '/home/prow/go/src/github.com/operate-first/apps/argocd/base' must resolve to a file': recursed accumulation of path '/home/prow/go/src/github.com/operate-first/apps/argocd/base': accumulating resources: accumulation err='accumulating resources from 'github.com/argoproj/argo-cd/manifests/base?ref=v2.0.1': evalsymlink failure on '/home/prow/go/src/github.com/operate-first/apps/argocd/base/github.com/argoproj/argo-cd/manifests/base?ref=v2.0.1' : lstat /home/prow/go/src/github.com/operate-first/apps/argocd/base/github.com: no such file or directory': hit 27s timeout running '/usr/bin/git fetch --depth=1 origin v2.0.1'
Aborting due to errexit on line 26. Exit code: 1 
```

going to keep digging

**Comment by HumairAK** [comment]
sanity checking, the remote manifests still exist: https://github.com/argoproj/argo-cd/tree/v2.0.1/manifests/base

**Comment by HumairAK** [comment]
Spinned up [this](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/operate-first_apps/765/kustomize-build/1405530611979915265 ) debug pod. 

Ran the test-kustomize-build script, still failed. So I tried checking out an [older commit from two days ago](https://github.com/operate-first/apps/commit/00c730349941fa0f413dbcf21e2cb9f167f60cab), and it still failed: 

```log
apps (master)$ oc debug 10fafafa-cf77-11eb-b3dc-0a580a82027a -c test
Starting pod/10fafafa-cf77-11eb-b3dc-0a580a82027a-debug, command was: /tools/entrypoint
Pod IP: 10.129.7.5
If you don't see a command prompt, try pressing enter.
sh-5.0$ git checkout 00c730349941fa0f413dbcf21e2cb9f167f60cab
...
HEAD is now at 00c7303 fix: Use common pull secret in MOC (#753)
sh-5.0$ test-kustomize-build 
checking ./acm/overlays/moc/infra
checking ./acme-operator/overlays/dev
checking ./acme-operator/overlays/moc/zero
checking ./alertreceiver/overlays/moc/common
checking ./alertreceiver/overlays/moc/infra
checking ./alertreceiver/overlays/moc/zero
checking ./argocd/overlays/dev/applications/dev_app
checking ./argocd/overlays/dev/applications
checking ./argocd/overlays/dev
Error: accumulating resources: accumulation err='accumulating resources from '../../base': '/home/prow/go/src/github.com/operate-first/apps/argocd/base' must resolve to a file': recursed accumulation of path '/home/prow/go/src/github.com/operate-first/apps/argocd/base': accumulating resources: accumulation err='accumulating resources from 'github.com/argoproj/argo-cd/manifests/base?ref=v2.0.1': evalsymlink failure on '/home/prow/go/src/github.com/operate-first/apps/argocd/base/github.com/argoproj/argo-cd/manifests/base?ref=v2.0.1' : lstat /home/prow/go/src/github.com/operate-first/apps/argocd/base/github.com: no such file or directory': hit 27s timeout running '/usr/bin/git fetch --depth=1 origin v2.0.1'
Aborting due to errexit on line 26. Exit code: 1
sh-5.0$ 
```

Confirming it's not the script: 
```
sh-5.0$ kustomize build argocd/base/
Error: accumulating resources: accumulation err='accumulating resources from 'github.com/argoproj/argo-cd/manifests/base?ref=v2.0.1': evalsymlink failure on '/home/prow/go/src/github.com/operate-first/apps/argocd/base/github.com/argoproj/argo-cd/manifests/base?ref=v2.0.1' : lstat /home/prow/go/src/github.com/operate-first/apps/argocd/base/github.com: no such file or directory': hit 27s timeout running '/usr/bin/git fetch --depth=1 origin v2.0.1'
sh-5.0$ 

```

**Comment by HumairAK** [comment]
So I tried running a `kustomize build` on the following yaml, in the debug pod and it seemed to work fine: 

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- https://github.com/kubernetes-sigs/kustomize/examples/multibases?ref=v1.0.6
```
So remote builds _do work_

**Comment by HumairAK** [comment]
The error indicates a time out on `hit 27s timeout running '/usr/bin/git fetch --depth=1 origin v2.0.1`, not sure if it's a red herring, but I don't see a way to increase this

**Comment by HumairAK** [comment]
The example given from the `kustomize build -h` command also fails for buildling from github: 

```
sh-5.0$ kustomize build https://github.com/kubernetes-sigs/kustomize.git/examples/helloWorld?ref=v1.0.6
Error: hit 27s timeout running '/usr/bin/git fetch --depth=1 origin v1.0.6'
```

**Comment by HumairAK** [comment]
Found: https://github.com/kubernetes-sigs/kustomize/issues/3742 
Not a lot of traffic though.

**Comment by HumairAK** [comment]
No luck finding out why the timeouts keep being hit in the prow pods, maybe it's slow networking? There seems to be more than enough compute usage when I run these builds in the pods. 

For now to unblock ci, we can rename the `argocd`, `overlays` folder to something else while we figure this out. None of the other apps seem affected, only `argocd` since that's the only one that seems to have a remote link.

**Comment by tumido** [comment]
I have better idea: https://github.com/operate-first/toolbox/pull/36

**Comment by HumairAK** [comment]
Look at this guy here trying to one up me by doing this _properly_ pfft.

**Comment by tumido** [comment]
Resolved via https://github.com/operate-first/toolbox/pull/36
