### ISSUE TITLE
Add Secrets to Kustomizations

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#77]
Please link all secrets that will need to be added as part of the kustomize builds in this repository. Once we have our secrets-management infrastructure in place, we'll use this thread as an aggregate point to update all kustomizations  that need to be updated.

**Comment by 4n4nd** [comment]
we'll need s3 creds for Loki (https://github.com/operate-first/apps/blob/master/observatorium/base/instance/example-loki-objectstorage-secret.yaml)

**Comment by hemajv** [comment]
We will need the auth token for sesheta for our GitHub alert manager (https://github.com/operate-first/apps/blob/master/odh/overlays/moc/monitoring/secrets/github-secret.enc.yaml)

**Comment by HumairAK** [comment]
Secrets management is in place, @4n4nd  and @hemajv  can we include these in their respective kustomizations now?

**Comment by hemajv** [comment]
> Secrets management is in place, @4n4nd and @hemajv can we include these in their respective kustomizations now?

done in #158 :+1:

**Comment by HumairAK** [comment]
@4n4nd update?

**Comment by 4n4nd** [comment]
> @4n4nd update?

still need to do it

**Comment by 4n4nd** [comment]
Loki creds were added in https://github.com/operate-first/apps/pull/334

**Comment by HumairAK** [comment]
Thanks @4n4nd !
