### ISSUE TITLE
GrafanaDashboards created using urls have stale jsons

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#803]
Currently the `GrafanaDashboard` resource needs to be deleted and recreate so that the json for the dashboard is fetched again from the url.

Relevant upstream issue: https://github.com/grafana-operator/grafana-operator/issues/440

**Comment by pacospace** [comment]
It worked for some CRD when we updated only the existing label, but not when adding the new label to the CRD. https://github.com/operate-first/apps/pull/787

**Comment by 4n4nd** [comment]
Unfortunately it didn't really work either one. I was just testing some things yesterday which applied the changes for one of them.

**Comment by 4n4nd** [comment]
I was able to make some changes in the operator upstream ([PR](https://github.com/grafana-operator/grafana-operator/pull/445)).
Now if we update the version number for a GrafanaDashboard object, it should pull the json form the specified url again.

**Comment by HumairAK** [comment]
seems like the pr was merged @4n4nd do we still need this issue?
