### ISSUE TITLE
Enable branch protection to prevent accidental pushes to master

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#81]
I accidentally pushed a commit to master (shameful [commit](https://github.com/operate-first/apps/commit/6dfab64bc0a4b705fde953cd2f9f063295432dbb)) and had to revert it. Can we disable commits to master in the org level?

**Comment by HumairAK** [comment]
I've put the following protections to prevent direct pushes to master: 
![image](https://user-images.githubusercontent.com/10904967/102106709-e6e9c680-3dfe-11eb-8f73-9deaffae8169.png)

I've also applied similar rules to the following repos: 
- toolbox
- argocd-apps
- continuous-deployment
- odh-moc-support
- sre

**Comment by 4n4nd** [comment]
@HumairAK do you want to add `main` branch as well?

**Comment by 4n4nd** [comment]
Also, instead of setting this for individual repos, I think this can be done org wide by an admin.
@durandom would that be okay?

**Comment by 4n4nd** [comment]
my bad, it looks like this can't be done on the org level :(

**Comment by HumairAK** [comment]
relevant issue [here](https://github.community/t/create-branch-protection-rules-at-an-organization-level/12368)

**Comment by HumairAK** [comment]
I'll leave this issue up for a couple of days in-case others have input/feedback on the protections I've added above.

**Comment by tumido** [comment]
I welcome this! :+1:

**Comment by durandom** [comment]
+1 on protected branches.

I also have git configured like

```
❯ g remote -vv                                                                      
origin	git@github.com:durandom/operate-first.github.io.git (fetch)
origin	git@github.com:durandom/operate-first.github.io.git (push)
upstream	https://github.com/operate-first/operate-first.github.io.git (fetch)
upstream	https://github.com/operate-first/operate-first.github.io.git (push)
```

Note, my upstream is a `https` URL, which I cannot push to, but read from. 
And "Merge UPstream" is aliased to:

```
❯ g mup --help
'mup' is aliased to '!git checkout master && git fetch upstream && git merge upstream/master && git push && git checkout -'
```

**Comment by HumairAK** [comment]
Looking for some feedback/discussion on the number of approvers. Right now it's 1. It helps get PR's in faster, but the cons are obvious. Less eyes, means more likely a problematic PR gets through. Upping this number can increase the rigor with which we merge our PR, but slow down and potentially block people as well.

**Comment by anishasthana** [comment]
I would strongly suggest 2. The only time we should be rushing PRs through is to resolve outages, etc.

**Comment by hemajv** [comment]
I'm a ++ for having at least 2 approvers, as it allows more people the chance to review PRs

**Comment by tumido** [comment]
I agree with that. That goes hand in hand with the need of having more people reviewing and more actively - actually trying out the things and not just skim through the code. Also, many folks can gain much needed experience with unfamiliar areas of our codebase, when they get the chance to start reviewing it. Everybody should be encouraged to review and should get the time they need.

That reminds me @anishasthana , did you have any luck with the research on round robin review assignments?

**Comment by anishasthana** [comment]
Not yet, I had some other work jump up and take priority. I'm wondering if Sesheta and Github are at odds with each other right now -- it seems like _all_ owners are assigned by Github for reviews as of now. Probably some other setting I'm missing.

**Comment by tumido** [comment]
@anishasthana  maybe the `CODEOWNERS` with `*` wildcard are messing with it? 

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by HumairAK** [comment]
Closing this issue, approvers were upped to 2 for the repositories listed above. If there's anything else that needs to be discussed, feel free to re-open.

**Comment by tumido** [comment]
I think it started a bit of a war between bots, see here: https://github.com/operate-first/apps/pull/51#issuecomment-756786786

We may want to think about this - either solve it somehow or stop using the `/approve` command. :confused: 

@goern @anishasthana  any thoughts?

**Comment by tumido** [comment]
@HumairAK @durandom ^

**Comment by HumairAK** [comment]
I think we should stop using the /approve command. I don't see any other way around it. Open to suggestions.

**Comment by HumairAK** [comment]
@harshad16 ^

**Comment by harshad16** [comment]
I m a bit confused on the front, as I was under the impression branch protection of 2 approvals, didn't stop prow from merging stuff with one approval. If it does do let us know. 

maybe stop using /approve command if there is such branch protection of 2 approvals seems to be the way to go.

**Comment by HumairAK** [comment]
@harshad16  It works for the operate-first repositories. I think I know what the problem @anishasthana  was having in the `aicoe-cd` repo ([here](https://github.com/AICoE/aicoe-cd/pull/198#issuecomment-742066380)). In the aicoe-cd repo, Sesheta is admin, so when applying branch protection, this check box needs to be enabled: 

![image](https://user-images.githubusercontent.com/10904967/104039286-2f996300-51a4-11eb-9d6d-cb4ef976e4c2.png)

The aicoe-cd repo does not have this checked, so the restriction does not apply to sesheta, and will merge it based on the label. We have checked this box for the operate-first repo, so it seems to be working. This is an example branch protection rule for this repo: 
![image](https://user-images.githubusercontent.com/10904967/104039501-738c6800-51a4-11eb-964b-81c2c314e782.png)

**Comment by harshad16** [comment]
Thanks for this information @HumairAK .

**Comment by HumairAK** [comment]
Closing this, if there's more to be discussed feel free to re-open.
