### ISSUE TITLE
Jupyterhub users Grafana dashboard doesn't reflect service outage

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/apps#817]
My notebook environment shows this:
![Screenshot from 2021-06-29 19-07-12](https://user-images.githubusercontent.com/8916126/123879106-ff19d100-d95d-11eb-823f-4f683fc48d80.png)
![Screenshot from 2021-06-29 19-07-21](https://user-images.githubusercontent.com/8916126/123879120-05a84880-d95e-11eb-9295-abd317bd8cb7.png)

If I try to restart I get this:
![Screenshot from 2021-06-29 19-12-35](https://user-images.githubusercontent.com/8916126/123879143-1062dd80-d95e-11eb-9b18-7763a565183e.png)

However, the JH dashboard still shows this:
![Screenshot from 2021-06-29 19-07-50](https://user-images.githubusercontent.com/8916126/123879164-1ce73600-d95e-11eb-8316-a9bb6a16a01b.png)

**Comment by tumido** [comment]
/kind bug

@4n4nd may this be related to https://github.com/operate-first/support/issues/291 (timeframe seems to match)

**Comment by Shreyanand** [comment]
Happened again:

![Screenshot from 2021-07-07 16-16-37](https://user-images.githubusercontent.com/8916126/124823568-fee98900-df8e-11eb-9599-28a422b8eb94.png)

![Screenshot from 2021-07-07 16-16-52](https://user-images.githubusercontent.com/8916126/124823581-014be300-df8f-11eb-9215-865e7f118284.png)

![Screenshot from 2021-07-07 16-19-06](https://user-images.githubusercontent.com/8916126/124823609-090b8780-df8f-11eb-8b05-22cdabff3a06.png)

![Screenshot from 2021-07-07 16-18-14](https://user-images.githubusercontent.com/8916126/124823596-04df6a00-df8f-11eb-90a4-7a3495379b73.png)
