### ISSUE TITLE
Override Vs Overlay and CRD rejection issue

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#87]
Related Issues: 
- #44 
- #85 

Recently we've been coming across situations where we'd prefer to overlay instead of override resources. The difference being, when we overlay, we are having argocd deploy them, whereas  with overriding in ODH, we have ODH deploy them. 

Context: 
So in some cases ODH deploys operators, which includes CRDs. Let's take for example KafkaTopics. Say I have ArgoCD deploy the KafkaTopics and a KFDef that deploys strimzi. Great, say ArgoCD tries to deploy `KafkaTopics` first, well it can't because it needs to deploy the KFDef first. So the application will fail. 

We can use ArgoCD `waves` to tell ArgoCD to deploy our kfdef (and thus Strimzi) first, then deploy `KafkaTopics` second. This too will fail because the ODH operator needs to read the KFDEF and deploy the CRDs itself. So we need ODH to deploy to the `KafkaTopics` by using overrides if we want to prevent errors from showing up. \

Problem:
I personally don't know if ODH is at a point where we can confidently override certain resources and expect to have them be sync'ed immediately. I have personally encountered situations where ODH will take a while to update the resources, sometimes having to restart ODH itself. I would be interested to hear what your own experiences have been.  

Another situation is, by being forced into override, we are forced into following the folder structure of the `odh-manifests` repo. For example if I want to override grafana dashboards, then I need to update this file [here](https://github.com/opendatahub-io/odh-manifests/blob/master/grafana/grafana/base/datasource.yaml). But what if I want to add another dashboard? The way I understand it  I would need to override the [kustomization here](https://github.com/opendatahub-io/odh-manifests/blob/master/grafana/grafana/base/kustomization.yaml). Okay, but then I have a kustomization, that looks like itt's pulling some files from this repo, and some files from another repo (and the other repo's existence isn't even clear right away by looking at this directory). It just seems messy to me. 

Yet another issue is that we cannot see kfdef child resources any more, see [here](https://github.com/kubeflow/kfctl/issues/460) for more details. So we have no sync/visual control over these resources via argocd.

**Comment by HumairAK** [comment]
Also note that this is only a problem for first deploys, once the CRDs are available, then using overlays doesn't result in any errors/issues. 

One solution I can think of is using waves, but with autosync turned on. We set KFDefs to always be deployed first, then everything else including CRs second, or later. Then when one tries to deploy components from this repo for the first time, they will see errors in the beginning, while ArgoCD (and thus ODH) deploys kfdef first. Since auto-sync is enabled, it will eventually resolve itself once ODH properly reconciles the CRDs.

**Comment by tumido** [comment]
> But what if I want to add another dashboard? The way I understand it I would need to override the kustomization here.

Not necessarily. There's a more convenient way. You can use overlays to further modify/add additional resources. Please take a look on how we approached this in the odh-dashboard deployment [here](https://github.com/operate-first/apps/tree/master/odh/base/dashboard):

We're adding "new" overlays used by the ODH operator. These overlays can introduce new resources as well as modify the base. In the case of `odh-dasboard` mentioned above, we're using both, we're adding 2 new overlays, both of which are then used in the `kfdef`:

- `custom-image` which overlays the base with a custom image -modifies the base
- `cluster-role` which adds a resource


But still, the issue is not solved by this.

**Comment by anishasthana** [comment]
I'm not quite seeing the issue with the override -- isn't the whole point of the ODH operator that you can use it to deploy your own manifests? So we'd change https://github.com/operate-first/apps/blob/master/odh/base/monitoring/kfdef.yaml#L48 to point at our own repo. We could have a fork of the upstream manifests that we sync on a regular basis (perhaps with every upstream release?) and keep adding our own changes onto it.

**Comment by tumido** [comment]
Honestly, I'm not sure about this. It's feels like we're trying to engineer a workaround for a workaround for bug in kubernetes.

I also don't see much of a problem with using overrides besides the observability. Which is a bug on kubeflow/kubernetes side.

All the resources we're talking about here are connected to the ODH deployment. And ODH is meant to be deployed by the ODH operator. But again, if overrides are the problem we can maintain a odh-manifests fork as Anish said. But I would rather see us keeping things in slim overrides and pushing them to upstream ODH as soon as we can.

**Comment by HumairAK** [comment]
It is my understanding that the point of override is so that we _don't_ have to fork the whole repo. 

One of my major concerns are actually resolved with what @tumido  has suggested above. 

I still think it's a bit unfortunate that we can't see some these resources in ArgoCD. And I expect we're going to encounter issues with odh taking a while to reconcile changes. But that's also something we should look to explore and report upstream.

I'll +1 for continuing to enforce everything via overrides then.

**Comment by anishasthana** [comment]
I'm fine with that too. Both overrides and fork seem reasonable to me, and fwiw I don't think a fork would be _that_ bad to keep running.

**Comment by HumairAK** [comment]
I trend here is to stick with overrides. 

If we're in an agreement on this, let's stick with overrides. I'll update the docs [here](https://github.com/operate-first/apps/tree/master/odh) to take a hard stance that any extension to odh should be done via overrides. 

We also need issues to move grafana dashaboards and kafkatopics into overrides and update docs for those accordingly. If there's anything else that should be restructured, please note them here. Link to this discussion as well in the PR. 

I'll leave this up for a day or two in-case others want to chime in as well.

**Comment by tumido** [comment]
I'll speculate here a bit. I have no intention to make this issue philosophical though, so take this comment with a grain of salt :smile:

I think the idea why to use overrides is also a bit deeper than that. It introduces a bit of discomfort which may motivate us to keep the changeset minimal and push us to stay closer to upstream.  This can maybe make us contribute the overridden content back to upstream to lower the maintenance costs.

This may come more obvious when compared to the "forked `odh-manifests` case". It's really easy to diverge the repo trees while it's very comfortable to contribute downstream only. And we have no motivation to push our changes upstream. We'd just "merge/rebase" each ODH release and that's it.
