### ISSUE TITLE
Enable monitoring for MOC/Smaug Cluster and send metrics to opf-observatorium Thanos

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#909]
Similar to https://github.com/operate-first/apps/issues/890

Tasks:

- [x] Enable User Workload Monitoring (https://github.com/operate-first/apps/pull/994)
- [x] Set up Openshift Monitoring with remote write to opf-observatorium thanos (https://github.com/operate-first/apps/pull/1391)

**Comment by 4n4nd** [comment]
| Application     | Service/PodMonitor | Alerts |
| ----------- | ----------- | ----------- |
| Grafana               | Done  |               |
| Kafka                   | Done  |               |
| ODH Operator     | Done  |               |
| Argo                     | Done  |               |
| Jupyterhub           | Done  |               |

**Comment by 4n4nd** [comment]
Related https://github.com/operate-first/apps/pull/1069

**Comment by tumido** [comment]
@4n4nd do we still need to deploy prometheus operator? We should avoid it as much as we can, since it's unsupported and may conflict with openshift-monitoring.
