### ISSUE TITLE
Remove namespaces from base, transfer to overlays for odh app

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#99]
We should remove the namespaces from base and assign these in the respective overlays, see #98 for more discussion.

**Comment by tumido** [comment]
@HumairAK is this issue still relevant? I think we can dismiss it now with the `cluster-scope` app presence.

**Comment by HumairAK** [comment]
I think we still need to do this for the odh app

**Comment by HumairAK** [comment]
I think after various restructuring since this issue was created, the initial reason for doing this is no longer applicable. Closing -- reopen if needed.
